#!/bin/bash
if [ ! -f /usr/bin/python2 ] ; then
    cd /usr/bin
    echo "python2 command not found"
    for PY in python2.* ; do
        if [ -f "$PY" ] ; then
            ln -s "$PY" python2
            echo "LINKING /usr/bin/$PY TO /usr/bin/python2"
            break
        fi
    done
    cd - > /dev/null
fi
