#!/bin/bash
cd /usr/bin
if [ ! -f python2 ] ; then
    echo "python2 command not found"
    for V in 2.7 2.6 ; do
        if [ -f "python$V" ] ; then
            ln -s "python$V" python2
            echo "LINKING /usr/bin/$PY TO /usr/bin/python2"
            break
        fi
    done
fi
cd - > /dev/null

