#!/usr/bin/env sh

nix-shell -p \
	python3Packages.pygobject3 \
	python3Packages.pycairo \
	python3Packages.pexpect \
	python3Packages.httplib2 \
	python3Packages.psutil \
	python3Packages.cachetools \
	python3Packages.requests \
	python3Packages.python-igraph \
	gtksourceview4 \
	lxqt.lxqt-openssh-askpass

