#!/bin/bash
## makes rpm package and installs it using zypper

## rpmbuild command is provided by package "rpm" that is a base and essential package is SUSE


if [ "$UID" != "0" ] ; then
  echo "Run this script as root"
  exit 1
fi


myPath="$0"
if [ "${myPath:0:2}" == "./" ] ; then
    myPath=$PWD${myPath:1}
elif [ "${myPath:0:1}" != "/" ] ; then
    myPath=$PWD/$myPath
fi


pkgName=starcal2
sourceDir="`dirname \"$myPath\"`"
"$sourceDir/scripts/assert_python2"
version=`$sourceDir/scal2/get_version.py`

#echo "myPath=$myPath"
#echo "sourceDir=$sourceDir"
#echo version=$version


requires=('python >= 2.6' 'python < 3.0')
requires+=('python-gtk >= 2.8')
#requires+=('python-gflags')
requires+=('python-httplib2')
requires+=('python-dateutil')

requires_str=$(printf "Requires: %s\n" "${requires[@]}")
requires_str+="
"

requires_str+="Recommends: python-igraph"

#echo "$requires_str"; exit



echo "Name: $pkgName
Version: $version
Release: 1
Summary: A full-featured international calendar writen in Python

Group: User Interface/Desktops
License: GPLv3+
URL: http://starcal.sourceforge.net/

$requires_str

BuildArch: noarch

%description
StarCalendar is a full-featured international calendar writen in Python,
with both PyGTK and PyQt interfaces, that supports Jalai(Iranian),
Hijri(Islamic), and Indian National calendars, as well as common 
english(Gregorian) calendar

%install
\"$sourceDir/install\" \"%{buildroot}\" --for-pkg --prefix=%{_prefix}

%post
/usr/share/starcal2/scripts/assert_python2

%files
%defattr(-,root,root,-)
%{_prefix}/share/starcal2/*
%{_prefix}/bin/starcal2*
%{_prefix}/share/applications/starcal2*
%{_prefix}/lib/bonobo/servers/GNOME_Starcal2Applet.server
%{_prefix}/share/doc/starcal2/*
%{_prefix}/share/pixmaps/starcal2.png
%{_prefix}/share/icons/hicolor/*/apps/starcal2.png
%{_prefix}/share/locale/*/LC_MESSAGES/starcal2.mo
" > $pkgName.spec

#less $pkgName.spec ; exit 0

pkgPath=`rpmbuild -bb $pkgName.spec | grep -o /usr/src/packages/RPMS/noarch/$pkgName.*\.rpm`
echo "pkgPath=$pkgPath"

if [ -z "$pkgPath" ] ; then
    echo "Package build failed"
    exit 1
fi
if [ ! -f "$pkgPath" ] ; then
    echo "Package file $pkgPath does not exit"
    exit 1
fi

echo "Package created in \"$pkgPath\", installing"

zypper install -f "$pkgPath"
## Problem: nothing provides /usr needed by starcal2-1.9.0-3.noarch
## Fixed with defining /usr as Provides

#if [ -f /usr/bin/yum ] ; then
#    yum remove -y $pkgName >/dev/null 2>&1
#    yum install --nogpgcheck "$pkgPath"
#fi

#rpm -U --force "$pkgPath" ## its OK when requiered packages are installed!

