#!/bin/bash
## makes rpm package and installs it using zypper

## rpmbuild command is provided by package "rpm" that is a base and essential package is SUSE

set -e

function check_pkg(){
	OUT=`zypper info "$1" | grep 'Installed:'`
	if [ "$OUT" = 'Installed: Yes' ] ; then
		echo 'installed'
	elif [ "$OUT" = 'Installed: No' ] ; then
		echo 'not_installed'
	else
		echo "not_found"
	fi
}

if [ "$UID" != "0" ] ; then
	echo "Run this script as root" >&2
	exit 1
fi

if ! git --version ; then
	if ! zypper install git-core ; then
		echo -e "\n\nPlease install git and try again" >&2
		exit 1
	fi
fi


pyCmd=
for minor in 7 6 ; do
	cmd="/usr/bin/python3.$minor"
	if [ -f "$cmd" ] ; then
		pyCmd="$cmd"
		break
	fi
done
if [ -z "$pyCmd" ] ; then
	echo "Please install python3.7 and try again (or python3.6)" >&2
	exit 1
fi
echo "Using python: \"$pyCmd\""
## --provides and --file-list both work
#pyPkg="`zypper search --match-exact --provides --installed-only \"$pyCmd\" | /bin/grep '^i |' | sed 's/i *| *//' | sed 's/ *|.*//g'`"
# if [ -z "$pyPkg" ] ; then
#	echo "Could not find python package name for \"$pyCmd\"" >&2
#	exit 1
#fi


myPath=$(realpath "$0")


pkgName=starcal3

sourceDir="`dirname \"$myPath\"`"

outDir="$HOME/.${pkgName}/pkgs/suse/`/bin/date +%F-%H%M%S`"
mkdir -p "$outDir"

"$sourceDir/pkg/suse/build.sh" "$outDir" "$pyCmd"
pkgPath=`ls -1 "$outDir"/*.rpm | tail -n1`

if [ -z "$pkgPath" ] ; then
	echo "Package build failed" >&2
	exit 1
fi
if [ ! -f "$pkgPath" ] ; then
	echo "Package file $pkgPath does not exit" >&2
	exit 1
fi

echo "Package created in \"$pkgPath\", installing"

zypper install -f --allow-unsigned-rpm "$pkgPath"

#rpm -U --force "$pkgPath" ## its OK when required packages are installed!

if [ "`check_pkg gnome-shell`" = installed ] ; then
	case `check_pkg gnome-shell-extension-topicons` in
		not_installed)
			zypper install gnome-shell-extension-topicons
			;;
		not_found)
			zypper ar -f http://download.opensuse.org/repositories/home:/PerryWerneck/openSUSE_13.2/ PerryWerneck && \
			zypper refresh && \
			zypper install gnome-shell-extension-topicons
			;;
	esac
fi


