#!/bin/bash
## install-fedora
## yum install @development-tools
## yum install rpm-build rpmdevtools rpmlint mock


if [ "$UID" != "0" ] ; then
  echo "Run this script as root"
  exit 1
fi


myPath="$0"
if [ "${myPath:0:2}" == "./" ] ; then
    myPath=$PWD${myPath:1}
elif [ "${myPath:0:1}" != "/" ] ; then
    myPath=$PWD/$myPath
fi


pkgName=starcal2
sourceDir="`dirname \"$myPath\"`"
version=`\$sourceDir/scal2/get_version.py`

#echo "myPath=$myPath"
#echo "sourceDir=$sourceDir"
#echo version=$version

tmpDir=/tmp/starcal2-install-deb
mkdir -p $tmpDir
cd $tmpDir




echo "Name:     $pkgName
Version:        $version
Release:        3
Summary:        A full-featured international calendar writen in Python

Group:          User Interface/Desktops
License:        GPLv3+
URL:            http://starcal.sourceforge.net/
Requires:       python(>=2.6), python(<<3.0), pygtk2(>=2.8), python-numpy
BuildArch:      noarch

%description
StarCalendar is a full-featured international calendar writen in Python,
with both PyGTK and PyQt interfaces, that supports Jalai(Iranian),
Hijri(Islamic), and Indian National calendars, as well as common 
english(Gregorian) calendar

%install
\"$sourceDir/install\" \"$tmpDir\" --for-pkg

%files
%defattr(-,root,root,-)
/usr/share/starcal2/*
/usr/bin/starcal2*
/usr/share/applications/starcal2*
/etc/init.d/starcal2d
/usr/lib/bonobo/servers/GNOME_Starcal2Applet.server
/usr/share/doc/starcal2/*
/usr/share/pixmaps/starcal2.png
/usr/share/icons/hicolor/*/apps/starcal2.png
/usr/share/locale/*/LC_MESSAGES/starcal2.mo

%changelog
" > "$tmpDir/$pkgName.spec"
## chown -R root "$tmpDir"

pkgPath=`rpmbuild -bb "$tmpDir/$pkgName.spec" | grep -o /usr/src/packages/RPMS.*rpm`
echo "pkgPath=$pkgPath"

if [ ! -f $pkgPath ] ; then
    exit 1
fi

echo "Package created in \"$pkgPath\", installing"
yum install "$pkgPath"

rm -R "$tmpDir"

