#!/bin/bash
## makes rpm package and installs it using yum

## yum install @development-tools
## yum install rpm-build rpmdevtools rpmlint mock


if [ "$UID" != "0" ] ; then
  echo "Run this script as root"
  exit 1
fi


myPath="$0"
if [ "${myPath:0:2}" == "./" ] ; then
    myPath=$PWD${myPath:1}
elif [ "${myPath:0:1}" != "/" ] ; then
    myPath=$PWD/$myPath
fi


pkgName=starcal2
sourceDir="`dirname \"$myPath\"`"
"$sourceDir/scripts/assert_python2"
version=`$sourceDir/scal2/get_version.py`

#echo "myPath=$myPath"
#echo "sourceDir=$sourceDir"
#echo version=$version



echo "Name:     $pkgName
Version:        $version
Release:        1
Summary:        A full-featured international calendar writen in Python

Group:          User Interface/Desktops
License:        GPLv3+
URL:            http://starcal.sourceforge.net/
Requires:       python(>=2.6), python(<<3.0), pygtk2(>=2.8), python-numpy
BuildArch:      noarch

%description
StarCalendar is a full-featured international calendar writen in Python,
with both PyGTK and PyQt interfaces, that supports Jalai(Iranian),
Hijri(Islamic), and Indian National calendars, as well as common 
english(Gregorian) calendar

%install
\"$sourceDir/install\" \"%{buildroot}\" --for-pkg --prefix=%{_prefix}

%files
%defattr(-,root,root,-)
%{_prefix}/share/starcal2/*
%{_prefix}/bin/starcal2*
%{_prefix}/share/applications/starcal2*
%{_prefix}/lib/bonobo/servers/GNOME_Starcal2Applet.server
%{_prefix}/share/doc/starcal2/*
%{_prefix}/share/pixmaps/starcal2.png
%{_prefix}/share/icons/hicolor/*/apps/starcal2.png
%{_prefix}/share/locale/*/LC_MESSAGES/starcal2.mo
/etc/init.d/starcal2d
" > $pkgName.spec

pkgPath=`rpmbuild -bb $pkgName.spec | grep -o /usr/src/packages/RPMS/.*rpm`
echo "pkgPath=$pkgPath"

if [ ! -f $pkgPath ] ; then
    echo "Package file $pkgPath does not exit"
    exit 1
fi

echo "Package created in \"$pkgPath\", installing"
yum remove -y $pkgName >/dev/null 2>&1
yum install --nogpgcheck "$pkgPath" ## disable gpgcheck in /etc/yum.conf
#rpm -U --force "$pkgPath" ## its OK when requiered packages are installed!

