#!/usr/bin/env sh

# Usage:
# sudo ./install-pip
# sudo ./install-pip 3.8

set -x

if [ "$(id -u)" != "0" ] ; then
	echo "Run this script as root" >&2
	exit 1
fi

./install-pip-deps "$@"
./distro/base/install.py --system
