#!/usr/bin/env bash

# Usage:
# sudo ./install-pip
# sudo ./install-pip 3.8

set -x

if [ "$UID" != "0" ] ; then
	echo "Run this script as root" >&2
	exit 1
fi

PIP=pip3
if [ -n "$1" ] ; then
	PIP="python$1 -m pip"
fi


$PIP install pygobject
$PIP install pycairo
$PIP install httplib2
$PIP install python-dateutil
$PIP install psutil
$PIP install requests

$PIP install ujson
$PIP install igraph
$PIP install pygit2

./install "$@"
