#!/usr/bin/env sh

# Usage:
# sudo ./install-pip
# sudo ./install-pip 3.8

set -x

if [ $(id -u) != "0" ] ; then
	echo "Run this script as root" >&2
	exit 1
fi

PIP=pip3
if [ -n "$1" ] ; then
	PIP="python$1 -m pip"
	shift
elif ! which $PIP ; then
	python3 -m ensurepip
fi


$PIP install pygobject
$PIP install pycairo
$PIP install httplib2
$PIP install python-dateutil
$PIP install psutil
$PIP install cachetools
$PIP install requests
$PIP install setuptools

$PIP install ujson
$PIP install python-igraph
$PIP install pygit2

if [ -f /bin/freebsd-version ] ; then
	./distro/base/install.py --system
else
	./install --system
fi
