#!/bin/bash
## makes PKGUILD and builds it (without root access), then installs it (prompts for password if necessary)

initPwd=$PWD

myPath="$0"
if [ "${myPath:0:2}" == "./" ] ; then
    myPath=$initPwd${myPath:1}
elif [ "${myPath:0:1}" != "/" ] ; then
    myPath=$initPwd/$myPath
fi


pkgName=starcal2
sourceDir="`dirname \"$myPath\"`"
"$sourceDir/scripts/assert_python2"
version=`$sourceDir/scal2/get_version.py`

tmpDir=/tmp/starcal2-install-arch
mkdir -p $tmpDir
cd $tmpDir

depends=('python2>=2.6')
depends+=('pygtk>=2.8')
depends+=('pygobject') ## The old "gobject" module
#depends+=('python2-gflags')
depends+=('python2-httplib2')
depends+=('python2-pytz')

optdepends=()
optdepends+=('python2-igraph')
#optdepends+=('python2-gnomeapplet')
optdepends+=('python2-gnomevfs')


depends_str=$(printf " '%s'" "${depends[@]}") ; depends_str=${depends_str:1}
optdepends_str=$(printf " '%s'" "${optdepends[@]}") ; optdepends_str=${optdepends_str:1}

echo "# Contributor: Saeed Rasooli <saeed.gnu@gmail.com>
# This is a local PKGBUILD
sourceDir='$sourceDir'
pkgname=$pkgName
pkgver=$version
pkgrel=1
pkgdesc='A full-featured international calendar writen in Python'
arch=('any')
url=(http://starcal.sourceforge.net)
license=('GPLv3')
depends=($depends_str)
optdepends=($optdepends_str)
makedepends=()
conflicts=('starcal-git')
source=()
md5sums=()
build() {
    \"\$sourceDir/install\" \"\$pkgdir\" --for-pkg
}" > PKGBUILD

makepkg -sif

cp $pkgName*.pkg.tar.?z "$initPwd"
echo "Package installed and copied into $initPwd directory"
cd "$initPwd"
rm -Rf $tmpDir

