#!/bin/bash

if [ "$UID" != "0" ] ; then
  echo "Run this script as root"
  exit 1
fi

pkgName=starcal2

#myPath="$0"
#if [ "${myPath:0:2}" == "./" ] ; then
#    myPath=$PWD${myPath:1}
#elif [ "${myPath:0:1}" != "/" ] ; then
#    myPath=$PWD/$myPath
#fi
#sourceDir="`dirname \"$myPath\"`"

prefix=/usr ## FIXME
sourceDir="$prefix/share/$pkgName"
"$sourceDir/assert_python2"
version=`\$sourceDir/scal2/get_version.py`


tmpDir=/tmp/starcal2-install-plasma
rm -R "$tmpDir" 2>/dev/null
mkdir -p "$tmpDir"
mkdir -p "$tmpDir/pkg"
mkdir -p "$tmpDir/pkg/contents"
mkdir -p "$tmpDir/pkg/contents/code"

cp "$sourceDir/scal2/ui_qt/plasma/main.py" "$tmpDir/pkg/contents/code/"
cp "$sourceDir/scal2/ui_qt/plasma/metadata.desktop" "$tmpDir/pkg"


plasmaPkgFile="$tmpDir/$pkgName-$version.plasmoid"
chown root "$tmpDir/pkg"
cd "$tmpDir/pkg"
zip -r "$plasmaPkgFile" .
cd - >/dev/null
plasmapkg -u -g "$plasmaPkgFile"
plasmoidviewer $pkgName
#plasmoidviewer -l "$plasmaPkgFile"

rm -R "$tmpDir"

