#!/bin/bash
## This script builds DEB package on a debian-based distribution
## (like debian, ubuntu, mint, ...) and installs the package

function getDirTotalSize(){
    du -bs "$1" | python2 -c "import sys;print raw_input().split('\t')[0]"
}

if [ "$UID" != "0" ] ; then
  echo "Run this script as root"
  exit 1
fi


myPath="$0"
if [ "${myPath:0:2}" == "./" ] ; then
    myPath=$PWD${myPath:1}
elif [ "${myPath:0:1}" != "/" ] ; then
    myPath=$PWD/$myPath
fi



pkgName=starcal2
sourceDir="`dirname \"$myPath\"`"
"$sourceDir/scripts/assert_python2"
version=`$sourceDir/scal2/get_version.py`


tmpDir=/tmp/starcal2-install-deb
mkdir -p $tmpDir
mkdir -p "$tmpDir/DEBIAN"

"$sourceDir/install" "$tmpDir" "--for-pkg"
chown -R root "$tmpDir"
installedSize=`getDirTotalSize "$tmpDir"` ## only /usr ? FIXME

#getDirTotalSize "$tmpDir"
#getDirTotalSize "$tmpDir/usr"


depends=('python(>=2.6)' 'python(<<3.0)')
depends+=('python-gtk2(>=2.8)')
depends+=('python-gflags')
depends+=('python-httplib2')
depends+=('python-tz')
depends+=('python-igraph')

if [ -f "/usr/lib/$HOSTTYPE-$OSTYPE/libappindicator.so.1" ] ; then
    depends+=('python-appindicator')
fi

depends_str=$(printf ", %s" "${depends[@]}") ; depends_str=${depends_str:2}
#echo $depends_str

echo "Package: $pkgName
Version: $version
Architecture: all
Maintainer: Saeed Rasooli <saeed.gnu@gmail.com>
Installed-Size: $installedSize
Depends: $depends_str
Recommends: 
Section: Utilities
Priority: optional
Homepage: http://starcal.sourceforge.net/
Description: A full-featured international calendar writen in Python
 StarCalendar is a full-featured international calendar writen in Python,
 with both PyGTK and PyQt interfaces, that supports Jalai(Iranian),
 Hijri(Islamic), and Indian National calendars, as well as common 
 english(Gregorian) calendar
 Homepage: http://starcal.sourceforge.net
" > "$tmpDir/DEBIAN/control"

echo "/usr/share/starcal2/scripts/assert_python2" > "$tmpDir/DEBIAN/postinst"
chmod 755 "$tmpDir/DEBIAN/postinst"

pkgFile=${pkgName}_${version}-1_all.deb
dpkg-deb -b "$tmpDir" "$pkgFile"
if [ "$?" = "0" ] ; then
    echo "Package file $pkgFile created, installing..."
    if [ -f /usr/bin/gdebi ] ; then
        /usr/bin/gdebi "$pkgFile"
    else
        dpkg -i "$pkgFile"
    fi
fi

rm -Rf "$tmpDir"

