#!/bin/bash
myPath="$0"
if [ "${myPath:0:2}" == "./" ] ; then
    myPath=$PWD${myPath:1}
elif [ "${myPath:0:1}" != "/" ] ; then
    myPath=$PWD/$myPath
fi
rootDir=`dirname "$myPath"`
PYTHONPATH=$PYTHONPATH:$rootDir python2 "$@"
