#!/usr/bin/env bash

cd "`dirname \"$0\"`"

#chmod -R 755 .

find . -type d -exec chmod 755 {} +

#find . -type f -exec chmod 644 '{}' \;

chmod 755 scripts/*

chmod 755 'starcal'

chmod 755 'scal3/ui_gtk/starcal.py'

chmod 755 'install'
chmod 755 'install-archlinux'
chmod 755 'install-debian'
chmod 755 'install-fedora'
chmod 755 'install-suse'
chmod 755 'install-ubuntu'
chmod 755 'uninstall'
chmod 755 'update-perm'

chmod 755 'locale.d/compile'
chmod 755 'locale.d/install'
chmod 755 'locale.d/make-template'

chmod 755 'scal3/get_version.py'
chmod 755 'scal3/import_config_2to3.py'

chmod 755 'scal3/ui_gtk/adjust_dtime.py'
chmod 755 'scal3/ui_gtk/arch-enable-locale.py'
chmod 755 'scal3/ui_gtk/import_config_2to3.py'
