#!/usr/bin/env sh
set -x

myDir=$(dirname "$0")
cd "$myDir"

#chmod -R 755 .

find . -type d -exec chmod 755 {} +

#find . -type f -exec chmod 644 '{}' \;

for F in scripts/* ; do
	if [ "$F" = scripts/__init__.py ] ; then
		continue
	fi
	chmod 755 "$F"
done

chmod 755 'starcal'

chmod 755 'scal3/ui_gtk/starcal.py'

chmod 755 'distro/base/install.sh'
chmod 755 'distro/base/install.py'
chmod 755 'distro/base/uninstall'

chmod 755 distro/*/install.sh

chmod 755 'install-ubuntu'
chmod 755 'install-pip'
chmod 755 'install-nix-deps'

chmod 755 distro/*/build.sh
chmod 755 distro/*/docker-build-internal.sh
chmod 755 distro/*/package-build.sh

chmod 755 'update-perm'

chmod 755 'locale.d/compile'
chmod 755 'locale.d/install'
chmod 755 'locale.d/make-template'

chmod 755 'scal3/ui_gtk/adjust_dtime.py'
chmod 755 'scal3/ui_gtk/arch-enable-locale.py'
