rtlImageNameMapping = {
	"go-next.svg": "go-previous.svg",
	"go-previous.svg": "go-next.svg",
}

iconNameByImageName = {
	"application-exit.svg": "gtk-quit",
	"applications-development-web.png": "",
	# "applications-graphics.svg": "applications-graphics",
	"applications-system.svg": "applications-system",
	"check-false.svg": "",
	"check-true.svg": "",
	# "computer.svg": "computer",
	"configure-toolbars.png": "",
	"dialog-cancel.svg": "gtk-cancel",
	"dialog-close.svg": "gtk-close",
	"dialog-error.svg": "gtk-dialog-error",
	"dialog-information.svg": "gtk-dialog-info",
	"dialog-ok-apply.svg": "gtk-apply",
	"dialog-ok.svg": "gtk-ok",
	"dialog-warning.svg": "gtk-dialog-warning",
	"document-edit.svg": "gtk-edit",
	# "document-new.svg": "gtk-new ",
	"document-save.svg": "gtk-save",
	"edit-copy.svg": "gtk-copy",
	"edit-cut.svg": "gtk-cut",
	"edit-delete.svg": "gtk-delete",
	"edit-find.png": "gtk-find",
	"edit-paste.svg": "gtk-paste",
	"edit-undo.svg": "gtk-undo",
	"evolution.png": "",
	"export-to-html.svg": "gtk-convert",
	"go-bottom.svg": "gtk-goto-bottom",
	"go-down.svg": "gtk-go-down",
	"go-home.svg": "gtk-home",
	"go-next.svg": "gtk-go-forward",
	"go-previous.svg": "gtk-go-back",
	"go-top.svg": "gtk-goto-top",
	"go-up.svg": "gtk-go-up",
	"help-about.svg": "gtk-about",
	"history.svg": "",
	"info.svg": "gtk-dialog-info",
	"list-add.svg": "gtk-add",
	"list-remove.svg": "gtk-remove",
	"media-playback-pause.svg": "gtk-media-pause",
	"media-playback-start.svg": "gtk-media-play",
	"media-playback-stop.svg": "gtk-media-stop",
	"movement.svg": "",
	"preferences-desktop-color.svg": "preferences-color",
	"preferences-desktop-locale.png": "preferences-desktop-locale",
	"preferences-desktop-theme.png": "preferences-desktop-theme",
	"preferences-plugin.svg": "",
	"preferences-system.svg": "gtk-preferences",
	"process-stop.svg": "process-stop",
	"resize-small.svg": "",
	"resize.svg": "",
	"screenruler.svg": "",
	"select-date.svg": "gtk-index",
	"starcal.svg": "",
	"sweep.svg": "gtk-clear",
	"switch-vertical.svg": "",
	# "sync-events.svg": "gtk-refresh",
	"text-calendar-ics.png": "",
	# "text-calendar.svg": "text-calendar",
	# "text-html.svg": "text-html",
	"timeline.svg": "",
	"transform-move.svg": "",
	"user-trash.svg": "user-trash",
	"view-calendar-timeline.svg": "",
	"view-refresh.svg": "gtk-refresh",
	"view-sort-ascending.svg": "gtk-sort-ascending",
	"week-calendar.svg": "",
	"window-close.svg": "gtk-close",
	"year-wheel.svg": "",
	"zoom-in.svg": "zoom-in",
	"zoom-question.svg": "",
}
