from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

from gi.repository import Gdk as gdk
from gi.repository import GObject

if TYPE_CHECKING:
	from gi.repository import Gtk as gtk

	from scal3.ui_gtk.pytypes import CustomizableCalObjType
	from scal3.ui_gtk.signals import SignalHandlerType

__all__ = ["MainWinType", "OptEvent", "OptWidget"]


type OptWidget = GObject.Object | None
type OptEvent = gdk.Event | None


class MainWinType(Protocol):
	win: gtk.ApplicationWindow
	w: gtk.Widget
	app: gtk.Application

	def onStatusIconClick(self, _w: OptWidget = None) -> None: ...
	def getStatusIconPopupItems(self) -> list[gtk.MenuItem]: ...
	def dayInfoShow(self, _sig: SignalHandlerType | None = None) -> None: ...
	def autoResize(self) -> None: ...
	def screenSizeChanged(self, rect: gdk.Rectangle) -> None: ...
	def statusIconUpdateTooltip(self) -> None: ...
	def goToday(self, _w: OptWidget = None) -> None: ...
	def selectDateShow(self, _w: OptWidget = None) -> None: ...
	def customizeShow(self, _w: OptWidget = None, _ge: OptEvent = None) -> None: ...
	def prefShow(self, _w: OptWidget = None, _ge: OptEvent = None) -> None: ...
	def eventManShow(self, _w: OptWidget = None, _ge: OptEvent = None) -> None: ...
	def onExportClick(self, _w: OptWidget = None) -> None: ...
	def aboutShow(self, _w: OptWidget = None, _data: Any = None) -> None: ...
	def onQuitClick(self, _w: OptWidget = None, _event: OptEvent = None) -> None: ...
	def childButtonPress(self, widget: gtk.Widget, gevent: gdk.EventButton) -> bool: ...
	def getMainWinMenuItem(self) -> gtk.MenuItem: ...

	def dayCalWinShow(self, _w: OptWidget = None, _ge: OptEvent = None) -> None: ...

	def menuMainPopup(
		self,
		_sig: SignalHandlerType,
		x: int,
		y: int,
		item: CustomizableCalObjType,
	) -> None: ...

	def menuCellPopup(
		self,
		_sig: SignalHandlerType,
		x: int,
		y: int,
		item: CustomizableCalObjType,
	) -> None: ...
