# Copyright (C) Saeed Rasooli <saeed.gnu@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.

from __future__ import annotations

from os.path import join
from typing import Any, NamedTuple

from scal3.color_utils import RGB, RGBA
from scal3.font import Font

__all__ = [
	"CUSTOMIZE",
	"DAYCAL_WIN_LIVE",
	"LIVE",
	"MAIN_CONF",
	"NEED_RESTART",
	"NOT_SET",
	"Font",
	"confParamsData",
	"getParamNamesWithFlag",
]

MAIN_CONF = 1
LIVE = 2
CUSTOMIZE = 4
NEED_RESTART = 8
DAYCAL_WIN_LIVE = 16


class NOT_SET:
	pass


class Param(NamedTuple):
	name: str
	v3Name: str
	flags: int
	type: str
	where: str = ""
	desc: str = ""
	default: Any = NOT_SET


confParamsData: list[Param] = [
	Param(
		name="mainWin.openOnStartup",
		v3Name="showMain",
		flags=MAIN_CONF,
		type="bool",
		where="Preferences: General",
		desc="Open main window on start",
		default=True,
	),
	Param(
		name="mainWin.inTaskbar",
		v3Name="winTaskbar",
		flags=MAIN_CONF | NEED_RESTART,
		type="bool",
		where="Preferences: General",
		desc="Window in Taskbar",
		default=False,
	),
	Param(
		name="useAppIndicator",
		v3Name="useAppIndicator",
		flags=MAIN_CONF | NEED_RESTART,
		type="bool",
		where="Preferences: General",
		desc="Use AppIndicator",
		default=True,
	),
	# ----------------- mainWin live info
	Param(
		name="mainWin.geo.x",
		v3Name="winX",
		flags=LIVE,
		type="int",
		where="MainWin: Move",
		desc="Window X",
		default=0,
	),
	Param(
		name="mainWin.geo.y",
		v3Name="winY",
		flags=LIVE,
		type="int",
		where="MainWin: Move",
		desc="Window Y",
		default=0,
	),
	Param(
		name="mainWin.geo.width",
		v3Name="winWidth",
		flags=LIVE,
		type="int",
		where="MainWin: Resize",
		desc="Window Width",
		default=480,
	),
	Param(
		name="mainWin.geo.height",
		v3Name="winHeight",
		flags=LIVE,
		type="int",
		where="MainWin: Resize",
		desc="Window Height",
		default=300,
	),
	Param(
		name="mainWin.keepAbove",
		v3Name="winKeepAbove",
		flags=LIVE,
		type="bool",
		where="MainWin: Menu",
		desc="On Top",
		default=True,
	),
	Param(
		name="mainWin.sticky",
		v3Name="winSticky",
		flags=LIVE,
		type="bool",
		where="MainWin: Menu",
		desc="On All Desktops",
		default=True,
	),
	Param(
		name="mainWin.maximized",
		v3Name="winMaximized",
		flags=LIVE,
		type="bool",
		where="MainWin: Window Controller: Maximize Window",
		desc="Window Maximized",
		default=False,
	),
	# ----------------- mainWin customize
	Param(
		name="mainWin.items",
		v3Name="mainWinItems",
		flags=CUSTOMIZE,
		type="list[tuple[str, bool]]",
		where="MainWin: Customize: Main Panel",
		desc="Items",
		default=[
			("toolbar", True),
			("labelBox", True),
			("monthCal", False),
			("weekCal", True),
			("dayCal", False),
			("monthPBar", False),
			("seasonPBar", True),
			("yearPBar", False),
		],
	),
	# -----------------= mainWin customize footer
	Param(
		name="mainWin.footer.items",
		v3Name="mainWinFooterItems",
		flags=CUSTOMIZE,
		type="list[str]",
		where="MainWin: Customize: (Footer)",
		desc="Footer Items",
		default=["pluginsText", "eventDayView", "statusBar"],
	),
	# ------------ pluginsText
	Param(
		name="mainWin.footer.pluginsText.enable",
		v3Name="pluginsTextEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: (Footer): Plugins Text",
		desc="Enable",
		default=False,
	),
	Param(
		name="mainWin.footer.pluginsText.insideExpander",
		v3Name="pluginsTextInsideExpander",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: (Footer): Plugins Text",
		desc="Inside Expander",
		default=True,
	),
	Param(
		name="mainWin.footer.pluginsText.isExpanded",
		v3Name="pluginsTextIsExpanded",
		flags=LIVE,
		type="bool",
		where="MainWin: (Footer): Plugins Text",
		desc="Is Expanded",
		default=True,
	),
	# ------------ eventDayView
	Param(
		name="mainWin.footer.eventDayView.enable",
		v3Name="eventDayViewEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: (Footer): Events of Day",
		desc="Enable",
		default=False,
	),
	Param(
		name="mainWin.footer.eventDayView.eventSep",
		v3Name="eventDayViewEventSep",
		flags=CUSTOMIZE,
		type="str",
		where="MainWin: Customize: (Footer): Events of Day",
		desc="Event Text Separator",
		default="\n",
	),
	Param(
		name="mainWin.footer.eventDayView.maxHeight",
		v3Name="eventViewMaxHeight",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: (Footer): Events of Day",
		desc="Maximum Height",
		default=200,
	),
	# ------------ statusBar
	Param(
		name="statusBar.enable",
		v3Name="statusBarEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: (Footer): Status Bar",
		desc="Enable",
		default=True,
	),
	Param(
		name="statusBar.dates.reverseOrder",
		v3Name="statusBarDatesReverseOrder",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: (Footer): Status Bar",
		desc="Reverse the order of dates",
		default=False,
	),
	Param(
		name="statusBar.dates.colorEnable",
		v3Name="statusBarDatesColorEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: (Footer): Status Bar",
		desc="Dates Color",
		default=False,
	),
	Param(
		name="statusBar.dates.color",
		v3Name="statusBarDatesColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: (Footer): Status Bar",
		desc="Dates Color",
		default=RGBA(255, 132, 255, 255),
	),
	# ----------------- Preferences: Appearance
	Param(
		name="fontCustomEnable",
		v3Name="fontCustomEnable",
		flags=MAIN_CONF,
		type="bool",
		where="Preferences: Appearance",
		desc="Application Font",
		default=False,
	),
	Param(
		name="fontCustom",
		v3Name="fontCustom",
		flags=MAIN_CONF,
		type="Font | None ",
		where="Preferences: Appearance",
		desc="Application Font",
		default=None,
	),
	Param(
		name="buttonIconEnable",
		v3Name="buttonIconEnable",
		flags=MAIN_CONF | NEED_RESTART,
		type="bool",
		where="Preferences: Appearance",
		desc="Show icons in buttons",
		default=True,
	),
	Param(
		name="useSystemIcons",
		v3Name="useSystemIcons",
		flags=MAIN_CONF | NEED_RESTART,
		type="bool",
		where="Preferences: Appearance",
		desc="Use System Icons",
		default=False,
	),
	Param(
		name="oldStyleProgressBar",
		v3Name="oldStyleProgressBar",
		flags=MAIN_CONF | NEED_RESTART,
		type="bool",
		where="Preferences: Appearance",
		desc="Old-style Progress Bar",
		default=False,
	),
	# ----------------- Preferences: Appearance: Colors
	Param(
		name="bgColor",
		v3Name="bgColor",
		flags=MAIN_CONF | LIVE,
		type="ColorType",
		where="Preferences: Appearance: Colors",
		desc="Background",
		default=RGBA(26, 0, 1, 255),
	),
	Param(
		name="borderColor",
		v3Name="borderColor",
		flags=MAIN_CONF,
		type="ColorType",
		where="Preferences: Appearance: Colors",
		desc="Border",
		default=RGBA(123, 40, 0, 255),
	),
	Param(
		name="borderTextColor",
		v3Name="borderTextColor",
		flags=MAIN_CONF,
		type="ColorType",
		where="Preferences: Appearance: Colors",
		desc="Border Font",
		default=RGBA(255, 255, 255, 255),
	),
	Param(
		name="textColor",
		v3Name="textColor",
		flags=MAIN_CONF,
		type="ColorType",
		where="Preferences: Appearance: Colors",
		desc="Normal Text",
		default=RGBA(255, 255, 255, 255),
	),
	Param(
		name="holidayColor",
		v3Name="holidayColor",
		flags=MAIN_CONF,
		type="ColorType",
		where="Preferences: Appearance: Colors",
		desc="Holidays Font",
		default=RGBA(255, 160, 0, 255),
	),
	Param(
		name="inactiveColor",
		v3Name="inactiveColor",
		flags=MAIN_CONF,
		type="ColorType",
		where="Preferences: Appearance: Colors",
		desc="Inactive Day Font",
		default=RGBA(255, 255, 255, 115),
	),
	Param(
		name="todayCellColor",
		v3Name="todayCellColor",
		flags=MAIN_CONF,
		type="ColorType",
		where="Preferences: Appearance: Colors",
		desc="Today",
		default=RGBA(0, 255, 0, 50),
	),
	Param(
		"cursorOutColor",
		v3Name="cursorOutColor",
		flags=MAIN_CONF,
		type="ColorType",
		where="Preferences: Appearance: Colors",
		desc="Cursor",
		default=RGBA(213, 207, 0, 255),
	),
	Param(
		name="cursorBgColor",
		v3Name="cursorBgColor",
		flags=MAIN_CONF,
		type="ColorType",
		where="Preferences: Appearance: Colors",
		desc="Cursor BG",
		default=RGBA(41, 41, 41, 255),
	),
	# ----------------- Preferences: Appearance: Status Icon
	Param(
		name="statusIcon.digitalClockEnable",
		v3Name="showDigClockTr",
		flags=MAIN_CONF,
		type="bool",
		where="Preferences: ... (not usable)",
		desc="Show Digital Clock: On Status Icon",
		default=True,
	),
	Param(
		name="statusIcon.imagePath",
		v3Name="statusIconImage",
		flags=MAIN_CONF,
		type="str",
		where="Preferences: Appearance: Status Icon",
		desc="Normal Days: Icon Path",
		default=join("status-icons", "dark-green.svg"),
	),
	Param(
		name="statusIcon.holidayImagePath",
		v3Name="statusIconImageHoli",
		flags=MAIN_CONF,
		type="str",
		where="Preferences: Appearance: Status Icon",
		desc="Holidays: Icon Path",
		default=join("status-icons", "dark-red.svg"),
	),
	Param(
		name="statusIcon.fontFamilyEnable",
		v3Name="statusIconFontFamilyEnable",
		flags=MAIN_CONF,
		type="bool",
		where="Preferences: Appearance: Status Icon",
		desc="[ ] Change font family to",
		default=False,
	),
	Param(
		name="statusIcon.fontFamily",
		v3Name="statusIconFontFamily",
		flags=MAIN_CONF,
		type="str | None",
		where="Preferences: Appearance: Status Icon",
		desc="Font family",
		default=None,
	),
	Param(
		name="statusIcon.holidayFontColorEnable",
		v3Name="statusIconHolidayFontColorEnable",
		flags=MAIN_CONF,
		type="bool",
		where="Preferences: Appearance: Status Icon",
		desc="Holiday font color",
		default=False,
	),
	Param(
		name="statusIcon.holidayFontColor",
		v3Name="statusIconHolidayFontColor",
		flags=MAIN_CONF,
		type="ColorType | None",
		where="Preferences: Appearance: Status Icon",
		desc="Holiday font color",
		default=None,
	),
	Param(
		name="statusIcon.localizeNumber",
		v3Name="statusIconLocalizeNumber",
		flags=MAIN_CONF,
		type="bool",
		where="Preferences: Appearance: Status Icon",
		desc="Localize the number",
		default=True,
	),
	Param(
		name="statusIcon.fixedSizeEnable",
		v3Name="statusIconFixedSizeEnable",
		flags=MAIN_CONF,
		type="bool",
		where="Preferences: Appearance: Status Icon",
		desc="[ ] Fixed Size",
		default=False,
	),
	Param(
		name="statusIcon.fixedSizeWH",
		v3Name="statusIconFixedSizeWH",
		flags=MAIN_CONF,
		type="tuple[int, int]",
		where="Preferences: Appearance: Status Icon",
		desc="Fixed Size (width, height)",
		default=(24, 24),
	),
	Param(
		name="statusIcon.pluginsText",
		v3Name="pluginsTextStatusIcon",
		flags=MAIN_CONF,
		type="bool",
		where="Preferences: Plugins",
		desc="Show in Status Icon (for today)",
		default=False,
	),
	# ----------------- Preferences: Advanced
	Param(
		name="maxDayCacheSize",
		v3Name="maxDayCacheSize",
		flags=MAIN_CONF,
		type="int",
		where="Preferences: Advanced",
		desc="Days maximum cache size",
		default=100,
	),
	Param(
		name="eventDayView.timeFormat",
		v3Name="eventDayViewTimeFormat",
		flags=MAIN_CONF,
		type="str",
		where="Preferences: Advanced",
		desc="Event Time Format",
		default="HM$",
	),
	Param(
		name="cellMenuHorizontalOffset",
		v3Name="cellMenuXOffset",
		flags=MAIN_CONF,
		type="int",
		where="Preferences: Advanced",
		desc="Horizontal offset for day right-click menu",
		default=0,
	),
	# TODO: ud.clockFormat: Digital Clock Format
	# ------------ Window Controller
	Param(
		name="winController.enable",
		v3Name="winControllerEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Window Controller",
		desc="Enable",
		default=True,
	),
	Param(
		name="winController.theme",
		v3Name="winControllerTheme",
		flags=CUSTOMIZE,
		type="str",
		where="MainWin: Customize: Window Controller",
		desc="Theme",
		default="default",
	),
	Param(
		name="winController.buttons",
		v3Name="winControllerButtons",
		flags=CUSTOMIZE,
		type="list[tuple[str, bool]]",
		where="MainWin: Customize: Window Controller",
		desc="Buttons",
		default=[
			("sep", True),
			("rightPanel", True),
			("min", True),
			("max", True),
			("close", True),
			("sep", False),
			("sep", False),
			("sep", False),
		],
	),
	Param(
		name="winController.iconSize",
		v3Name="winControllerIconSize",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Window Controller",
		desc="Icon Size",
		default=24,
	),
	Param(
		name="winController.border",
		v3Name="winControllerBorder",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Window Controller",
		desc="Buttons Border",
		default=0,
	),
	Param(
		name="winController.spacing",
		v3Name="winControllerSpacing",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Window Controller",
		desc="Space between buttons",
		default=0,
	),
	Param(
		name="winController.pressState",
		v3Name="winControllerPressState",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Window Controller",
		desc="Change icon on button press",
		default=False,
	),
	# ------------ rightPanel
	Param(
		name="rightPanel.enable",
		v3Name="mainWinRightPanelEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Right Panel",
		desc="Enable",
		default=True,
	),
	Param(
		name="rightPanel.heightRatio",
		v3Name="mainWinRightPanelRatio",
		flags=LIVE,
		type="float",
		where="MainWin: Right Panel",
		desc="Ration of height of upper half to the whole",
		default=0.5,
	),
	Param(
		name="rightPanel.swap",
		v3Name="mainWinRightPanelSwap",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Right Panel: Context menu",
		desc="Swap Plugins Text and Events Text",
		default=False,
	),
	Param(
		name="rightPanel.width",
		v3Name="mainWinRightPanelWidth",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Right Panel: Sizes",
		desc="Width: Fixed width",
		default=200,
	),
	Param(
		name="rightPanel.widthRatio",
		v3Name="mainWinRightPanelWidthRatio",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Right Panel: Sizes",
		desc="Width: Relative to window",
		default=0.25,
	),
	Param(
		name="rightPanel.widthRatioEnable",
		v3Name="mainWinRightPanelWidthRatioEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Right Panel: Sizes",
		desc="Width: Relative to window",
		default=True,
	),
	Param(
		name="rightPanel.event.fontEnable",
		v3Name="mainWinRightPanelEventFontEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Right Panel: Events Text",
		desc="Font",
		default=False,
	),
	Param(
		name="rightPanel.event.font",
		v3Name="mainWinRightPanelEventFont",
		flags=CUSTOMIZE,
		type="Font | None",
		where="MainWin: Customize: Right Panel: Events Text",
		desc="Font",
		default=None,
	),
	Param(
		"rightPanel.event.timeFontEnable",
		v3Name="mainWinRightPanelEventTimeFontEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Right Panel: Events Text",
		desc="Time Font",
		default=False,
	),
	Param(
		name="rightPanel.event.timeFont",
		v3Name="mainWinRightPanelEventTimeFont",
		flags=CUSTOMIZE,
		type="Font | None",
		where="MainWin: Customize: Right Panel: Events Text",
		desc="Time Font",
		default=None,
	),
	Param(
		name="rightPanel.event.justification",
		v3Name="mainWinRightPanelEventJustification",
		flags=CUSTOMIZE,
		type="str",  # left, center, right
		where="MainWin: Customize: Right Panel: Events Text",
		desc="Text Alignment",
		default="left",
	),
	Param(
		name="rightPanel.event.sep",
		v3Name="mainWinRightPanelEventSep",
		flags=CUSTOMIZE,
		type="str",
		where="MainWin: Customize: Right Panel: Events Text",
		desc="Event Text Separator",
		default="\n\n",
	),
	Param(
		name="rightPanel.plugins.fontEnable",
		v3Name="mainWinRightPanelPluginsFontEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Right Panel: Plugins Text",
		desc="Font",
		default=False,
	),
	Param(
		name="rightPanel.plugins.font",
		v3Name="mainWinRightPanelPluginsFont",
		flags=CUSTOMIZE,
		type="Font | None",
		where="MainWin: Customize: Right Panel: Plugins Text",
		desc="Font",
		default=None,
	),
	Param(
		name="rightPanel.plugins.justification",
		v3Name="mainWinRightPanelPluginsJustification",
		flags=CUSTOMIZE,
		type="str",  # left, center, right
		where="MainWin: Customize: Right Panel: Plugins Text",
		desc="Text Alignment",
		default="left",
	),
	Param(
		name="rightPanel.resizeOnToggle",
		v3Name="mainWinRightPanelResizeOnToggle",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Right Panel",
		desc="Resize on show/hide from window controller",
		default=True,
	),
	Param(
		name="rightPanel.border",
		v3Name="mainWinRightPanelBorderWidth",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Right Panel",
		desc="Border Width",
		default=7,
	),
	# ------------ Month Calendar
	Param(
		name="monthCal.leftMargin",
		v3Name="mcalLeftMargin",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Month Calendar",
		desc="Left Margin",
		default=30,
	),
	Param(
		name="monthCal.topMargin",
		v3Name="mcalTopMargin",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Month Calendar",
		desc="Top Margin",
		default=30,
	),
	Param(
		name="monthCal.typeParams",
		v3Name="mcalTypeParams",
		flags=CUSTOMIZE,
		type="list[CalTypeParamsDict]",
		where="MainWin: Customize: Month Calendar",
		desc="Calendar Types Params",
		default=[
			{"pos": (0, -2), "font": None, "color": (220, 220, 220)},
			{"pos": (18, 5), "font": None, "color": (165, 255, 114)},
			{"pos": (-18, 4), "font": None, "color": (0, 200, 205)},
		],
	),
	Param(
		name="monthCal.grid",
		v3Name="mcalGrid",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Month Calendar",
		desc="Grid",
		default=False,
	),
	Param(
		name="monthCal.gridColor",
		v3Name="mcalGridColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Month Calendar",
		desc="Grid Color",
		default=RGBA(255, 252, 0, 82),
	),
	Param(
		name="monthCal.cornerMenuTextColor",
		v3Name="mcalCornerMenuTextColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Month Calendar",
		desc="Corner Menu Text Color",
		default=RGBA(255, 255, 255, 255),
	),
	Param(
		name="monthCal.cursorLineWidthFactor",
		v3Name="mcalCursorLineWidthFactor",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Month Calendar: Cursor",
		desc="Line Width Factor",
		default=0.12,
	),
	Param(
		name="monthCal.cursorRoundingFactor",
		v3Name="mcalCursorRoundingFactor",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Month Calendar: Cursor",
		desc="Rounding Factor",
		default=0.5,
	),
	# ------------ weekcal
	Param(
		name="weekCal.textSizeScale",
		v3Name="wcalTextSizeScale",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Week Calendar",
		desc="Text Size Scale",
		default=0.6,
	),
	Param(
		name="weekCal.items",
		v3Name="wcalItems",
		flags=CUSTOMIZE,
		type="list[tuple[str, bool]]",
		where="MainWin: Customize: Week Calendar",
		desc="Items",
		default=[
			("toolbar", True),
			("weekDays", True),
			("pluginsText", True),
			("eventsIcon", True),
			("eventsText", True),
			("daysOfMonth", True),
		],
	),
	Param(
		name="weekCal.grid",
		v3Name="wcalGrid",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar",
		desc="Grid ",
		default=False,
	),
	Param(
		name="weekCal.gridColor",
		v3Name="wcalGridColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Week Calendar",
		desc="Grid Color",
		default=RGBA(255, 252, 0, 82),
	),
	Param(
		name="weekCal.upperGradientEnable",
		v3Name="wcalUpperGradientEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar",
		desc="Row's Upper Gradient",
		default=False,
	),
	Param(
		name="weekCal.upperGradientColor",
		v3Name="wcalUpperGradientColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Week Calendar",
		desc="Row's Upper Gradient",
		default=RGBA(255, 255, 255, 60),
	),
	Param(
		name="weekCal.eventsText.pastColorEnable",
		v3Name="wcal_eventsText_pastColorEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Events Text",
		desc="Past Event Color",
		default=False,
	),
	Param(
		name="weekCal.eventsText.pastColor",
		v3Name="wcal_eventsText_pastColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Week Calendar: Columns: Events Text",
		desc="Past Event Color",
		default=RGBA(100, 100, 100, 50),
	),
	Param(
		name="weekCal.eventsText.ongoingColorEnable",
		v3Name="wcal_eventsText_ongoingColorEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Events Text",
		desc="Ongoing Event Color",
		default=False,
	),
	Param(
		name="weekCal.eventsText.ongoingColor",
		v3Name="wcal_eventsText_ongoingColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Week Calendar: Columns: Events Text",
		desc="Ongoing Event Color",
		default=RGBA(80, 255, 80, 255),
	),
	Param(
		name="weekCal.eventsText.showDesc",
		v3Name="wcal_eventsText_showDesc",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Events Text",
		desc="Show Description",
		default=False,
	),
	Param(
		name="weekCal.eventsText.colorize",
		v3Name="wcal_eventsText_colorize",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: ",
		desc="Use color of event group for event text",
		default=True,
	),
	Param(
		name="weekCal.eventsText.fontFamily",
		v3Name="wcalFont_eventsText",
		flags=CUSTOMIZE,
		type="str | None",
		where="MainWin: Customize: Week Calendar: Columns: ",
		desc="Font Family",
		default=None,
	),
	Param(
		name="weekCal.toolbar.weekNumNegative",
		v3Name="wcal_toolbar_weekNum_negative",
		flags=LIVE,
		type="bool",
		where="MainWin: Week Calendar: Toolbar",
		desc="Week number is negated by clicking",
		default=False,
	),
	Param(
		name="weekCal.toolbar.mainMenuIcon",
		v3Name="wcal_toolbar_mainMenu_icon",
		flags=CUSTOMIZE,
		type="str",
		where="MainWin: Customize: Week Calendar: Columns: Toolbar: Main Menu",
		desc="Icon",
		default="starcal.png",
	),
	Param(
		name="weekCal.weekDays.width",
		v3Name="wcal_weekDays_width",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Week Calendar: Columns: Week Days",
		desc="Width",
		default=80,
	),
	Param(
		name="weekCal.weekDays.expand",
		v3Name="wcal_weekDays_expand",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Week Days",
		desc="Expand",
		default=False,
	),
	Param(
		name="weekCal.weekDays.fontFamily",
		v3Name="wcalFont_weekDays",
		flags=CUSTOMIZE,
		type="str | None",
		where="MainWin: Customize: Week Calendar: Columns: Week Days",
		desc="Font Family",
		default=None,
	),
	Param(
		name="weekCal.pluginsText.fontFamily",
		v3Name="wcalFont_pluginsText",
		flags=CUSTOMIZE,
		type="str | None",
		where="MainWin: Customize: Week Calendar: Columns: Plugins Text",
		desc="Font Family",
		default=None,
	),
	Param(
		name="weekCal.pluginsText.firstLineOnly",
		v3Name="wcal_pluginsText_firstLineOnly",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Plugins Text",
		desc="Only first line of text",
		default=False,
	),
	Param(
		name="weekCal.eventsIcon.width",
		v3Name="wcal_eventsIcon_width",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Week Calendar: Columns: Events Icon",
		desc="Width",
		default=50,
	),
	Param(
		name="weekCal.daysOfMonth.typeParams",
		v3Name="wcalTypeParams",
		flags=CUSTOMIZE,
		type="list[WeekCalDayNumParamsDict]",
		where="MainWin: Customize: Week Calendar: Columns: Days of Month",
		desc="Font (for each calendar type)",
		default=[{"font": None}, {"font": None}, {"font": None}],
	),
	Param(
		name="weekCal.daysOfMonth.direction",
		v3Name="wcal_daysOfMonth_dir",
		flags=CUSTOMIZE,
		type="str",  # ltr, rtl, auto
		where="MainWin: Customize: Week Calendar: Columns: Days of Month",
		desc="Direction",
		default="ltr",
	),
	Param(
		name="weekCal.daysOfMonth.width",
		v3Name="wcal_daysOfMonth_width",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Week Calendar: Columns: Days of Month",
		desc="Width",
		default=30,
	),
	Param(
		name="weekCal.daysOfMonth.expand",
		v3Name="wcal_daysOfMonth_expand",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: ",
		desc="Width",
		default=False,
	),
	Param(
		name="weekCal.eventsCount.width",
		v3Name="wcal_eventsCount_width",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Week Calendar: Columns: ",
		desc="Width",
		default=80,
	),
	Param(
		name="weekCal.eventsCount.expand",
		v3Name="wcal_eventsCount_expand",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: ",
		desc="Expand",
		default=False,
	),
	Param(
		name="weekCal.eventsBox.fontFamily",
		v3Name="wcalFont_eventsBox",
		flags=CUSTOMIZE,
		type="str | None",
		where="MainWin: Customize: Week Calendar: Columns: Events Box",
		desc="Font Family",
		default=None,
	),
	Param(
		name="weekCal.moonStatus.width",
		v3Name="wcal_moonStatus_width",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Week Calendar: Columns: Moon Status",
		desc="Width",
		default=48,
	),
	Param(
		name="weekCal.moonStatus.southernHemisphere",
		v3Name="wcal_moonStatus_southernHemisphere",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Moon Status",
		desc="Southern Hemisphere",
		default=False,
	),
	Param(
		name="weekCal.cursorLineWidthFactor",
		v3Name="wcalCursorLineWidthFactor",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Week Calendar: Cursor",
		desc="Line Width Factor",
		default=0.12,
	),
	Param(
		name="weekCal.cursorRoundingFactor",
		v3Name="wcalCursorRoundingFactor",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Week Calendar: Cursor",
		desc="Rounding Factor",
		default=0.5,
	),
	# ------------ daycal
	Param(
		name="dayCal.widgetButtonsEnable",
		v3Name="dcalWidgetButtonsEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Day Calendar: Buttons",
		desc="Widget buttons",
		default=False,
	),
	# Param("dayCal.widgetButtons", "dcalWidgetButtons", CUSTOMIZE),
	Param(
		name="dayCal.day.params",
		v3Name="dcalDayParams",
		flags=CUSTOMIZE,
		type="list[DayCalTypeDayParamsDict]",
		where="MainWin: Customize: Day Calendar: {Calendar Type}",
		desc="[Enable, Position, Alignment, Font, Color]",
		default=[
			{
				"pos": (0, -12),
				"font": None,
				"color": (220, 220, 220),
				"enable": True,
				"xalign": "center",
				"yalign": "center",
			},
			{
				"pos": (125, 30),
				"font": None,
				"color": (165, 255, 114),
				"enable": True,
				"xalign": "center",
				"yalign": "center",
			},
			{
				"pos": (-125, 24),
				"font": None,
				"color": (0, 200, 205),
				"enable": True,
				"xalign": "center",
				"yalign": "center",
			},
		],
	),
	Param(
		name="dayCal.month.params",
		v3Name="dcalMonthParams",
		flags=CUSTOMIZE,
		type="list[DayCalTypeWMParamsDict]",
		where="MainWin: Customize: Day Calendar: {Calendar Type}: Month Name",
		desc="[Enable, Position, Alignment, Font, Color]",
		default=[
			{
				"pos": (0, -12),
				"font": None,
				"color": (220, 220, 220),
				"enable": False,
				"xalign": "center",
				"yalign": "center",
				"abbreviate": False,
				"uppercase": False,
			},
			{
				"pos": (125, 30),
				"font": None,
				"color": (165, 255, 114),
				"enable": False,
				"xalign": "center",
				"yalign": "center",
				"abbreviate": False,
				"uppercase": False,
			},
			{
				"pos": (-125, 24),
				"font": None,
				"color": (0, 200, 205),
				"enable": False,
				"xalign": "center",
				"yalign": "center",
				"abbreviate": False,
				"uppercase": False,
			},
		],
	),
	Param(
		name="dayCal.weekday.params",
		v3Name="dcalWeekdayParams",
		flags=CUSTOMIZE,
		type="DayCalTypeWMParamsDict",
		where="MainWin: Customize: Day Calendar: Week Day",
		desc="[Enable, Position, Alignment, Font, Color]",
		default={
			"pos": (20, 10),
			"font": None,
			"color": (0, 200, 205),
			"enable": False,
			"xalign": "right",
			"yalign": "buttom",
			"abbreviate": False,
			"uppercase": False,
		},
	),
	Param(
		name="dayCal.navButtons.enable",
		v3Name="dcalNavButtonsEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Day Calendar: Buttons",
		desc="Navigation buttons",
		default=True,
	),
	Param(
		# FIXME: where is the GUI?
		name="dayCal.navButtons.geo",
		v3Name="dcalNavButtonsGeo",
		flags=CUSTOMIZE,
		type="ButtonGeoDict",
		where="MainWin: Customize: Day Calendar: Buttons",
		desc="Navigation Buttons",
		default={
			"auto_rtl": True,
			"size": 64,
			"spacing": 10,
			"pos": (0, 20),
			"xalign": "center",
			"yalign": "buttom",
		},
	),
	Param(
		# FIXME: where is the GUI?
		name="dayCal.navButtons.opacity",
		v3Name="dcalNavButtonsOpacity",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Day Calendar: Buttons",
		desc="Navigation Buttons Opacity",
		default=0.7,
	),
	Param(
		name="dayCal.weekday.localize",
		v3Name="dcalWeekdayLocalize",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Day Calendar: Week Day",
		desc="Localize",
		default=True,
	),
	Param(
		name="dayCal.weekday.abbreviate",
		v3Name="dcalWeekdayAbbreviate",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Day Calendar: Week Day",
		desc="Abbreviate",
		default=False,
	),
	Param(
		name="dayCal.weekday.uppercase",
		v3Name="dcalWeekdayUppercase",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Day Calendar: Week Day",
		desc="Uppercase",
		default=False,
	),
	Param(
		name="dayCal.event.iconSize",
		v3Name="dcalEventIconSize",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Day Calendar: Events",
		desc="Icon Size",
		default=20,
	),
	Param(
		name="dayCal.event.totalSizeRatio",
		v3Name="dcalEventTotalSizeRatio",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Day Calendar: Events",
		desc="Total Size Ratio",
		default=0.3,
	),
	# ------------ dayCalWin
	Param(
		name="dayCalWin.enable",
		v3Name="showDesktopWidget",
		flags=MAIN_CONF,
		type="bool",
		where="Preferences: General",
		desc="Open desktop widget on start",
		default=False,
	),
	Param(
		name="dayCalWin.geo.x",
		v3Name="dcalWinX",
		flags=DAYCAL_WIN_LIVE,
		type="int",
		where="DayCalWin: Move",
		desc="Geometry: X",
		default=0,
	),
	Param(
		name="dayCalWin.geo.y",
		v3Name="dcalWinY",
		flags=DAYCAL_WIN_LIVE,
		type="int",
		where="DayCalWin: Move",
		desc="Geometry: Y",
		default=0,
	),
	Param(
		name="dayCalWin.geo.width",
		v3Name="dcalWinWidth",
		flags=DAYCAL_WIN_LIVE,
		type="int",
		where="DayCalWin: Resize",
		desc="Geometry: Width",
		default=180,
	),
	Param(
		name="dayCalWin.geo.height",
		v3Name="dcalWinHeight",
		flags=DAYCAL_WIN_LIVE,
		type="int",
		where="DayCalWin: Resize",
		desc="Geometry: Height",
		default=180,
	),
	Param(
		name="dayCalWin.backgroundColor",
		v3Name="dcalWinBackgroundColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize",
		desc="Background Color",
		default=RGB(0, 10, 0),
	),
	Param(
		name="dayCalWin.widgetButtons.enable",
		v3Name="dcalWinWidgetButtonsEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="DayCalWin: Customize: Buttons",
		desc="Widget buttons",
		default=True,
	),
	Param(
		name="dayCalWin.widgetButtons.size",
		v3Name="dcalWinWidgetButtonsSize",
		flags=CUSTOMIZE,
		type="int",
		where="DayCalWin: Customize: Buttons",
		desc="Widget buttons Size",
		default=16,
	),
	Param(
		name="dayCalWin.widgetButtons.opacity",
		v3Name="dcalWinWidgetButtonsOpacity",
		flags=CUSTOMIZE,
		type="float",
		where="DayCalWin: Customize: Buttons",
		desc="Widget buttons Opacity",
		default=1.0,
	),
	# Param("dayCalWin.widgetButtons", "dcalWinWidgetButtons", CUSTOMIZE),
	Param(
		name="dayCalWin.weekday.localize",
		v3Name="dcalWinWeekdayLocalize",
		flags=CUSTOMIZE,
		type="bool",
		where="DayCalWin: Customize: Week Day",
		desc="Localize",
		default=True,
	),
	Param(
		name="dayCalWin.weekday.abbreviate",
		v3Name="dcalWinWeekdayAbbreviate",
		flags=CUSTOMIZE,
		type="bool",
		where="DayCalWin: Customize: Week Day",
		desc="Abbreviate",
		default=False,
	),
	Param(
		name="dayCalWin.weekday.uppercase",
		v3Name="dcalWinWeekdayUppercase",
		flags=CUSTOMIZE,
		type="bool",
		where="DayCalWin: Customize: Week Day",
		desc="Uppercase",
		default=False,
	),
	Param(
		name="dayCalWin.day.params",
		v3Name="dcalWinDayParams",
		flags=CUSTOMIZE,
		type="list[DayCalTypeDayParamsDict]",
		where="DayCalWin: Customize: {Calendar Type}",
		desc="[Enable, Position, Alignment, Font, Color]",
		default=[
			{
				"pos": (0, 5),
				"font": None,
				"color": (220, 220, 220),
				"enable": True,
				"xalign": "left",
				"yalign": "center",
			},
			{
				"pos": (5, 0),
				"font": None,
				"color": (165, 255, 114),
				"enable": True,
				"xalign": "right",
				"yalign": "top",
			},
			{
				"pos": (0, 0),
				"font": None,
				"color": (0, 200, 205),
				"enable": True,
				"xalign": "right",
				"yalign": "buttom",
			},
		],
	),
	Param(
		name="dayCalWin.month.params",
		v3Name="dcalWinMonthParams",
		flags=CUSTOMIZE,
		type="list[DayCalTypeWMParamsDict]",
		where="DayCalWin: Customize: {Calendar Type}: Month Name",
		desc="[Enable, Position, Alignment, Font, Color]",
		default=[
			{
				"pos": (0, 5),
				"font": None,
				"color": (220, 220, 220),
				"enable": False,
				"xalign": "left",
				"yalign": "center",
				"abbreviate": False,
				"uppercase": False,
			},
			{
				"pos": (5, 0),
				"font": None,
				"enable": False,
				"color": (165, 255, 114),
				"xalign": "right",
				"yalign": "top",
				"abbreviate": False,
				"uppercase": False,
			},
			{
				"pos": (0, 0),
				"font": None,
				"color": (0, 200, 205),
				"enable": False,
				"xalign": "right",
				"yalign": "buttom",
				"abbreviate": False,
				"uppercase": False,
			},
		],
	),
	Param(
		name="dayCalWin.weekday.params",
		v3Name="dcalWinWeekdayParams",
		flags=CUSTOMIZE,
		type="DayCalTypeWMParamsDict",
		where="DayCalWin: Customize: Week Day",
		desc="[Enable, Position, Alignment, Font, Color]",
		# TODO: add abbreviate and uppercase
		default={
			"pos": (20, 10),
			"font": None,
			"color": (0, 200, 205),
			"enable": False,
			"xalign": "right",
			"yalign": "buttom",
			"abbreviate": False,
			"uppercase": False,
		},
	),
	Param(
		name="dayCalWin.event.iconSize",
		v3Name="dcalWinEventIconSize",
		flags=CUSTOMIZE,
		type="int",
		where="DayCalWin: Customize: Events",
		desc="Icon Size",
		default=20,
	),
	Param(
		name="dayCalWin.event.totalSizeRatio",
		v3Name="dcalWinEventTotalSizeRatio",
		flags=CUSTOMIZE,
		type="float",
		where="DayCalWin: Customize: Events",
		desc="Total Size Ratio",
		default=0.3,
	),
	Param(
		name="dayCalWin.seasonPie.enable",
		v3Name="dcalWinSeasonPieEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="DayCalWin: Customize: Season Pie",
		desc="Enable",
		default=False,
	),
	Param(
		name="dayCalWin.seasonPie.geo",
		v3Name="dcalWinSeasonPieGeo",
		flags=CUSTOMIZE,
		type="PieGeoDict",
		where="DayCalWin: Customize: Season Pie",
		desc="Geometry",
		default={
			"size": 64,
			"thickness": 0.3,
			"pos": (0, 0),
			"xalign": "right",
			"yalign": "top",
			"startAngle": 270,
		},
	),
	Param(
		name="dayCalWin.seasonPie.springColor",
		v3Name="dcalWinSeasonPieSpringColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize: Season Pie",
		desc="Spring Color",
		default=RGBA(167, 252, 1, 180),
	),
	Param(
		name="dayCalWin.seasonPie.summerColor",
		v3Name="dcalWinSeasonPieSummerColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize: Season Pie",
		desc="Summer Color",
		default=RGBA(255, 254, 0, 180),
	),
	Param(
		name="dayCalWin.seasonPie.autumnColor",
		v3Name="dcalWinSeasonPieAutumnColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize: Season Pie",
		desc="Autumn Color",
		default=RGBA(255, 127, 0, 180),
	),
	Param(
		name="dayCalWin.seasonPie.winterColor",
		v3Name="dcalWinSeasonPieWinterColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize: Season Pie",
		desc="Winter Color",
		default=RGBA(1, 191, 255, 180),
	),
	Param(
		name="dayCalWin.seasonPie.textColor",
		v3Name="dcalWinSeasonPieTextColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize: Season Pie",
		desc="Text Color",
		default=RGBA(255, 255, 255, 180),
	),
	# ------------ progress bars
	Param(
		name="monthPBar.calType",
		v3Name="monthPBarCalType",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Main Panel: Month Progress Bar",
		desc="Calendar Type",
		default=-1,
	),
	Param(
		name="seasonPBar.southernHemisphere",
		v3Name="seasonPBar_southernHemisphere",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Main Panel: Season Progress Bar",
		desc="Southern Hemisphere",
		default=False,
	),
	# ------------
	Param(
		name="yearMonthBar.border",
		v3Name="labelBoxBorderWidth",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Border Width",
		default=0,
	),
	Param(
		name="yearMonthBar.menuActiveColor",
		v3Name="labelBoxMenuActiveColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Active menu item color",
		default=RGBA(0, 255, 0, 255),
	),
	Param(
		name="yearMonthBar.yearColorEnable",
		v3Name="labelBoxYearColorEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Year Color",
		default=False,
	),
	Param(
		name="yearMonthBar.yearColor",
		v3Name="labelBoxYearColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Year Color",
		default=RGBA(255, 132, 255, 255),
	),
	Param(
		name="yearMonthBar.monthColorEnable",
		v3Name="labelBoxMonthColorEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Month Color",
		default=False,
	),
	Param(
		name="yearMonthBar.monthColor",
		v3Name="labelBoxMonthColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Month Color",
		default=RGBA(255, 132, 255, 255),
	),
	Param(
		name="yearMonthBar.fontEnable",
		v3Name="labelBoxFontEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Font",
		default=False,
	),
	Param(
		name="yearMonthBar.font",
		v3Name="labelBoxFont",
		flags=CUSTOMIZE,
		type="Font | None",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Font",
		default=None,
	),
	Param(
		name="yearMonthBar.primaryFontEnable",
		v3Name="labelBoxPrimaryFontEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Primary Calendar Font",
		default=False,
	),
	Param(
		name="yearMonthBar.primaryFont",
		v3Name="labelBoxPrimaryFont",
		flags=CUSTOMIZE,
		type="Font | None",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Primary Calendar Font",
		default=None,
	),
	Param(
		name="yearMonthBar.boldYearMonth",
		v3Name="boldYmLabel",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Main Panel: Year & Month Bar",
		desc="Bold Font",
		default=True,
	),
	# ------------
	Param(
		name="weekCal.toolbar.items",
		v3Name="ud__wcalToolbarData",
		flags=CUSTOMIZE,
		type="CustomizableToolBoxDict | None",
		where="MainWin: Customize: Main Panel: Week Calendar: Columns/; Toolbar",
		desc="Toolbar Buttons",
		default=None,
	),
	Param(
		name="mainWin.toolbar.items",
		v3Name="ud__mainToolbarData",
		flags=CUSTOMIZE,
		type="CustomizableToolBoxDict | None",
		where="MainWin: Customize: Main Panel: Toolbar",
		desc="Toolbar Buttons",
		default=None,
	),
	# ----------------- Other
	Param(
		name="preferencesPagePath",
		v3Name="preferencesPagePath",
		flags=MAIN_CONF,
		type="str",
		where="Preferences",
		desc="Preferences Page Path",
		default="",
	),
	Param(
		name="customizePagePath",
		v3Name="customizePagePath",
		flags=CUSTOMIZE,
		type="str",
		where="Customize",
		desc="Customize Page Path",
		default="",
	),
	# move to a new file like local-tz.json?
	Param(
		name="localTimezoneHistory",
		v3Name="localTzHist",
		flags=MAIN_CONF,
		type="list[str]",
		where="-",
		desc="Local Timezone History",
		default=[],
	),
	# ----------------- Not currently save / loaded
	Param(
		name="",
		v3Name="showDigClockTb",
		flags=0,
		type="bool",
		where="Preferences: ... (not usable)",
		desc="Show Digital Clock: On Toolbar",
		default=True,
	),
	Param(
		name="",
		v3Name="menuIconPadding",
		flags=0,
		type="int",
		where="-",
		desc="Menu Icon Padding",
		default=7,
	),
	Param(
		name="",
		v3Name="eventTreeGroupIconSize",
		flags=0,
		type="int",
		where="",
		desc="Event Tree Group Icon Size",
		default=24,
	),
	Param(
		name="",
		v3Name="treeIconSize",
		flags=0,
		type="int",
		where="",
		desc="Tree Icon Size",
		default=22,
	),
	Param(
		name="",
		v3Name="labelBoxIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=20,
	),
	Param(
		name="",
		v3Name="stackIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=22,
	),
	Param(
		name="",
		v3Name="dcalWidgetButtons",
		flags=0,
		type="list[dict[str, Any]]",
		where="",
		desc="",
		default=[
			{
				"imageName": "transform-move.svg",
				"onClick": "startMove",
				"pos": (0, 0),
				"xalign": "left",
				"yalign": "top",
				"autoDir": False,
			},
			{
				"imageName": "resize-small.svg",
				"onClick": "startResize",
				"pos": (1, 1),
				"xalign": "right",
				"yalign": "buttom",
				"autoDir": False,
			},
		],
	),
	Param(
		name="",
		v3Name="dcalWinWidgetButtons",
		flags=0,
		type="list[dict[str, Any]]",
		where="",
		desc="",
		default=[
			{
				"imageName": "transform-move.svg",
				"onClick": "startMove",
				"pos": (0, 0),
				"xalign": "left",
				"yalign": "top",
				"autoDir": False,
			},
			{
				"imageName": "resize-small.svg",
				"onClick": "startResize",
				"pos": (1, 1),
				"xalign": "right",
				"yalign": "buttom",
				"autoDir": False,
			},
			{
				"imageName": "document-edit.svg",
				"onClick": "openCustomize",
				"pos": (0, 1),
				"xalign": "left",
				"yalign": "buttom",
				"autoDir": False,
			},
		],
	),
	Param(
		name="",
		v3Name="menuIconEdgePadding",
		flags=0,
		type="int",
		where="",
		desc="",
		default=3,
	),
	Param(
		name="",
		v3Name="rightPanelEventIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=20,
	),
	Param(
		name="",
		v3Name="eventTreeIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=22,
	),
	Param(
		name="",
		v3Name="menuEventCheckIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=20,
	),
	Param(
		name="",
		v3Name="toolbarIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=24,
	),
	Param(
		name="",
		v3Name="mcalEventIconSizeMax",
		flags=0,
		type="int",
		where="",
		desc="",
		default=26,
	),
	Param(
		name="",
		v3Name="messageDialogIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=48,
	),
	Param(
		name="",
		v3Name="menuCheckSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=22,
	),
	Param(
		name="",
		v3Name="menuIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=18,
	),
	Param(
		name="",
		v3Name="comboBoxIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=20,
	),
	Param(
		name="",
		v3Name="imageInputIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=32,
	),
	Param(
		name="",
		v3Name="maxWeekCacheSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=12,
	),
	Param(
		name="",
		v3Name="wcalPadding",
		flags=0,
		type="int",
		where="",
		desc="",
		default=10,
	),
	Param(
		name="",
		v3Name="buttonIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=20,
	),
	Param(
		name="",
		v3Name="wcalEventIconSizeMax",
		flags=0,
		type="int",
		where="",
		desc="",
		default=26,
	),
	Param(
		name="",
		v3Name="eventWeekViewTimeFormat",
		flags=0,
		type="str",
		where="",
		desc="",
		default="HM$",
	),
]

_v3Names = [p.v3Name for p in confParamsData]
assert len(_v3Names) == len(set(_v3Names))


def getParamNamesWithFlag(flag: int) -> list[str]:
	return [p.v3Name for p in confParamsData if p.flags & flag > 0]
