# Copyright (C) Saeed Rasooli <saeed.gnu@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.

from __future__ import annotations

from scal3.color_utils import RGB, RGBA
from scal3.ui.options._base import CUSTOMIZE, DAYCAL_WIN_LIVE, MAIN_CONF, OptionData

confOptionsData: list[OptionData] = [
	# ------------ daycal
	OptionData(
		name="dayCal.widgetButtonsEnable",
		v3Name="dcalWidgetButtonsEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Day Calendar: Buttons",
		desc="Widget buttons",
		default=False,
	),
	# Param("dayCal.widgetButtons", "dcalWidgetButtons", CUSTOMIZE),
	OptionData(
		name="dayCal.day.options",
		v3Name="dcalDayParams",
		flags=CUSTOMIZE,
		type="list[DayCalTypeDayOptionsDict]",
		where="MainWin: Customize: Day Calendar: {Calendar Type}",
		desc="[Enable, Position, Alignment, Font, Color]",
		default=[
			{
				"pos": (0, -12),
				"font": None,
				"color": (220, 220, 220),
				"enable": True,
				"xalign": "center",
				"yalign": "center",
				"localize": False,
			},
			{
				"pos": (125, 30),
				"font": None,
				"color": (165, 255, 114),
				"enable": True,
				"xalign": "center",
				"yalign": "center",
				"localize": False,
			},
			{
				"pos": (-125, 24),
				"font": None,
				"color": (0, 200, 205),
				"enable": True,
				"xalign": "center",
				"yalign": "center",
				"localize": False,
			},
		],
	),
	OptionData(
		name="dayCal.month.options",
		v3Name="dcalMonthParams",
		flags=CUSTOMIZE,
		type="list[DayCalTypeWMOptionsDict]",
		where="MainWin: Customize: Day Calendar: {Calendar Type}: Month Name",
		desc="[Enable, Position, Alignment, Font, Color]",
		default=[
			{
				"pos": (0, -12),
				"font": None,
				"color": (220, 220, 220),
				"enable": False,
				"xalign": "center",
				"yalign": "center",
				"abbreviate": False,
				"uppercase": False,
			},
			{
				"pos": (125, 30),
				"font": None,
				"color": (165, 255, 114),
				"enable": False,
				"xalign": "center",
				"yalign": "center",
				"abbreviate": False,
				"uppercase": False,
			},
			{
				"pos": (-125, 24),
				"font": None,
				"color": (0, 200, 205),
				"enable": False,
				"xalign": "center",
				"yalign": "center",
				"abbreviate": False,
				"uppercase": False,
			},
		],
	),
	OptionData(
		name="dayCal.weekday.options",
		v3Name="dcalWeekdayParams",
		flags=CUSTOMIZE,
		type="DayCalTypeWMOptionsDict",
		where="MainWin: Customize: Day Calendar: Week Day",
		desc="[Enable, Position, Alignment, Font, Color]",
		default={
			"pos": (20, 10),
			"font": None,
			"color": (0, 200, 205),
			"enable": False,
			"xalign": "right",
			"yalign": "buttom",
			"abbreviate": False,
			"uppercase": False,
		},
	),
	OptionData(
		name="dayCal.navButtons.enable",
		v3Name="dcalNavButtonsEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Day Calendar: Buttons",
		desc="Navigation buttons",
		default=True,
	),
	OptionData(
		# no GUI for it yet
		name="dayCal.navButtons.geo",
		v3Name="dcalNavButtonsGeo",
		flags=0,
		type="ButtonGeoDict",
		where="MainWin: Customize: Day Calendar: Buttons",
		desc="Navigation Buttons",
		default={
			"autoDir": True,
			"size": 64,
			"spacing": 10,
			"pos": (0, 20),
			"xalign": "center",
			"yalign": "buttom",
		},
	),
	OptionData(
		# FIXME: where is the GUI?
		name="dayCal.navButtons.opacity",
		v3Name="dcalNavButtonsOpacity",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Day Calendar: Buttons",
		desc="Navigation Buttons Opacity",
		default=0.7,
	),
	OptionData(
		name="dayCal.weekday.localize",
		v3Name="dcalWeekdayLocalize",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Day Calendar: Week Day",
		desc="Localize",
		default=True,
	),
	OptionData(
		name="dayCal.weekday.abbreviate",
		v3Name="dcalWeekdayAbbreviate",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Day Calendar: Week Day",
		desc="Abbreviate",
		default=False,
	),
	OptionData(
		name="dayCal.weekday.uppercase",
		v3Name="dcalWeekdayUppercase",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Day Calendar: Week Day",
		desc="Uppercase",
		default=False,
	),
	OptionData(
		name="dayCal.event.iconSize",
		v3Name="dcalEventIconSize",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Day Calendar: Events",
		desc="Icon Size",
		default=20,
	),
	OptionData(
		name="dayCal.event.totalSizeRatio",
		v3Name="dcalEventTotalSizeRatio",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Day Calendar: Events",
		desc="Total Size Ratio",
		default=0.3,
	),
	# ------------ dayCalWin
	OptionData(
		name="dayCalWin.enable",
		v3Name="showDesktopWidget",
		flags=MAIN_CONF,
		type="bool",
		where="Preferences: General",
		desc="Open desktop widget on start",
		default=True,
	),
	OptionData(
		name="dayCalWin.geo.x",
		v3Name="dcalWinX",
		flags=DAYCAL_WIN_LIVE,
		type="int",
		where="DayCalWin: Move",
		desc="Geometry: X",
		default=0,
	),
	OptionData(
		name="dayCalWin.geo.y",
		v3Name="dcalWinY",
		flags=DAYCAL_WIN_LIVE,
		type="int",
		where="DayCalWin: Move",
		desc="Geometry: Y",
		default=0,
	),
	OptionData(
		name="dayCalWin.geo.width",
		v3Name="dcalWinWidth",
		flags=DAYCAL_WIN_LIVE,
		type="int",
		where="DayCalWin: Resize",
		desc="Geometry: Width",
		default=180,
	),
	OptionData(
		name="dayCalWin.geo.height",
		v3Name="dcalWinHeight",
		flags=DAYCAL_WIN_LIVE,
		type="int",
		where="DayCalWin: Resize",
		desc="Geometry: Height",
		default=180,
	),
	OptionData(
		name="dayCalWin.backgroundColor",
		v3Name="dcalWinBackgroundColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize",
		desc="Background Color",
		default=RGB(0, 10, 0),
	),
	OptionData(
		name="dayCalWin.widgetButtons.enable",
		v3Name="dcalWinWidgetButtonsEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="DayCalWin: Customize: Buttons",
		desc="Widget buttons",
		default=True,
	),
	OptionData(
		name="dayCalWin.widgetButtons.size",
		v3Name="dcalWinWidgetButtonsSize",
		flags=CUSTOMIZE,
		type="int",
		where="DayCalWin: Customize: Buttons",
		desc="Widget buttons Size",
		default=16,
	),
	OptionData(
		name="dayCalWin.widgetButtons.opacity",
		v3Name="dcalWinWidgetButtonsOpacity",
		flags=CUSTOMIZE,
		type="float",
		where="DayCalWin: Customize: Buttons",
		desc="Widget buttons Opacity",
		default=1.0,
	),
	# Param("dayCalWin.widgetButtons", "dcalWinWidgetButtons", CUSTOMIZE),
	OptionData(
		name="dayCalWin.weekday.localize",
		v3Name="dcalWinWeekdayLocalize",
		flags=CUSTOMIZE,
		type="bool",
		where="DayCalWin: Customize: Week Day",
		desc="Localize",
		default=True,
	),
	OptionData(
		name="dayCalWin.weekday.abbreviate",
		v3Name="dcalWinWeekdayAbbreviate",
		flags=CUSTOMIZE,
		type="bool",
		where="DayCalWin: Customize: Week Day",
		desc="Abbreviate",
		default=False,
	),
	OptionData(
		name="dayCalWin.weekday.uppercase",
		v3Name="dcalWinWeekdayUppercase",
		flags=CUSTOMIZE,
		type="bool",
		where="DayCalWin: Customize: Week Day",
		desc="Uppercase",
		default=False,
	),
	OptionData(
		name="dayCalWin.day.options",
		v3Name="dcalWinDayParams",
		flags=CUSTOMIZE,
		type="list[DayCalTypeDayOptionsDict]",
		where="DayCalWin: Customize: {Calendar Type}",
		desc="[Enable, Position, Alignment, Font, Color]",
		default=[
			{
				"pos": (0, 5),
				"font": None,
				"color": (220, 220, 220),
				"enable": True,
				"xalign": "left",
				"yalign": "center",
				"localize": False,
			},
			{
				"pos": (5, 0),
				"font": None,
				"color": (165, 255, 114),
				"enable": True,
				"xalign": "right",
				"yalign": "top",
				"localize": False,
			},
			{
				"pos": (0, 0),
				"font": None,
				"color": (0, 200, 205),
				"enable": True,
				"xalign": "right",
				"yalign": "buttom",
				"localize": False,
			},
		],
	),
	OptionData(
		name="dayCalWin.month.options",
		v3Name="dcalWinMonthParams",
		flags=CUSTOMIZE,
		type="list[DayCalTypeWMOptionsDict]",
		where="DayCalWin: Customize: {Calendar Type}: Month Name",
		desc="[Enable, Position, Alignment, Font, Color]",
		default=[
			{
				"pos": (0, 5),
				"font": None,
				"color": (220, 220, 220),
				"enable": False,
				"xalign": "left",
				"yalign": "center",
				"abbreviate": False,
				"uppercase": False,
			},
			{
				"pos": (5, 0),
				"font": None,
				"enable": False,
				"color": (165, 255, 114),
				"xalign": "right",
				"yalign": "top",
				"abbreviate": False,
				"uppercase": False,
			},
			{
				"pos": (0, 0),
				"font": None,
				"color": (0, 200, 205),
				"enable": False,
				"xalign": "right",
				"yalign": "buttom",
				"abbreviate": False,
				"uppercase": False,
			},
		],
	),
	OptionData(
		name="dayCalWin.weekday.options",
		v3Name="dcalWinWeekdayParams",
		flags=CUSTOMIZE,
		type="DayCalTypeWMOptionsDict",
		where="DayCalWin: Customize: Week Day",
		desc="[Enable, Position, Alignment, Font, Color]",
		# TODO: add abbreviate and uppercase
		default={
			"pos": (20, 10),
			"font": None,
			"color": (0, 200, 205),
			"enable": False,
			"xalign": "right",
			"yalign": "buttom",
			"abbreviate": False,
			"uppercase": False,
		},
	),
	OptionData(
		name="dayCalWin.event.iconSize",
		v3Name="dcalWinEventIconSize",
		flags=CUSTOMIZE,
		type="int",
		where="DayCalWin: Customize: Events",
		desc="Icon Size",
		default=20,
	),
	OptionData(
		name="dayCalWin.event.totalSizeRatio",
		v3Name="dcalWinEventTotalSizeRatio",
		flags=CUSTOMIZE,
		type="float",
		where="DayCalWin: Customize: Events",
		desc="Total Size Ratio",
		default=0.3,
	),
	OptionData(
		name="dayCalWin.seasonPie.enable",
		v3Name="dcalWinSeasonPieEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="DayCalWin: Customize: Season Pie",
		desc="Enable",
		default=False,
	),
	OptionData(
		name="dayCalWin.seasonPie.geo",
		v3Name="dcalWinSeasonPieGeo",
		flags=CUSTOMIZE,
		type="PieGeoDict",
		where="DayCalWin: Customize: Season Pie",
		desc="Geometry",
		default={
			"size": 64,
			"thickness": 0.3,
			"pos": (0, 0),
			"xalign": "right",
			"yalign": "top",
			"startAngle": 270,
		},
	),
	OptionData(
		name="dayCalWin.seasonPie.springColor",
		v3Name="dcalWinSeasonPieSpringColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize: Season Pie",
		desc="Spring Color",
		default=RGBA(167, 252, 1, 180),
	),
	OptionData(
		name="dayCalWin.seasonPie.summerColor",
		v3Name="dcalWinSeasonPieSummerColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize: Season Pie",
		desc="Summer Color",
		default=RGBA(255, 254, 0, 180),
	),
	OptionData(
		name="dayCalWin.seasonPie.autumnColor",
		v3Name="dcalWinSeasonPieAutumnColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize: Season Pie",
		desc="Autumn Color",
		default=RGBA(255, 127, 0, 180),
	),
	OptionData(
		name="dayCalWin.seasonPie.winterColor",
		v3Name="dcalWinSeasonPieWinterColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize: Season Pie",
		desc="Winter Color",
		default=RGBA(1, 191, 255, 180),
	),
	OptionData(
		name="dayCalWin.seasonPie.textColor",
		v3Name="dcalWinSeasonPieTextColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="DayCalWin: Customize: Season Pie",
		desc="Text Color",
		default=RGBA(255, 255, 255, 180),
	),
]
