# Copyright (C) Saeed Rasooli <saeed.gnu@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.

from __future__ import annotations

from scal3.ui.options._base import CUSTOMIZE, MAIN_CONF, OptionData

confOptionsData: list[OptionData] = [
	# ----------------- Other
	OptionData(
		name="preferencesPagePath",
		v3Name="preferencesPagePath",
		flags=MAIN_CONF,
		type="str",
		where="Preferences",
		desc="Preferences Page Path",
		default="",
	),
	OptionData(
		name="customizePagePath",
		v3Name="customizePagePath",
		flags=CUSTOMIZE,
		type="str",
		where="Customize",
		desc="Customize Page Path",
		default="",
	),
	# move to a new file like local-tz.json?
	OptionData(
		name="localTimezoneHistory",
		v3Name="localTzHist",
		flags=MAIN_CONF,
		type="list[str]",
		where="-",
		desc="Local Timezone History",
		default=[],
	),
	# ----------------- Not currently save / loaded
	OptionData(
		name="",
		v3Name="showDigClockTb",
		flags=0,
		type="bool",
		where="Preferences: ... (not usable)",
		desc="Show Digital Clock: On Toolbar",
		default=True,
	),
	OptionData(
		name="",
		v3Name="menuIconPadding",
		flags=0,
		type="int",
		where="-",
		desc="Menu Icon Padding",
		default=7,
	),
	OptionData(
		name="",
		v3Name="eventTreeGroupIconSize",
		flags=0,
		type="int",
		where="",
		desc="Event Tree Group Icon Size",
		default=24,
	),
	OptionData(
		name="",
		v3Name="treeIconSize",
		flags=0,
		type="int",
		where="",
		desc="Tree Icon Size",
		default=22,
	),
	OptionData(
		name="",
		v3Name="labelBoxIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=20,
	),
	OptionData(
		name="",
		v3Name="stackIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=22,
	),
	OptionData(
		name="",
		v3Name="dcalWidgetButtons",
		flags=0,
		type="list[DayCalWidgetButtonDict]",
		where="",
		desc="",
		default=[
			{
				"imageName": "transform-move.svg",
				"onClick": "startMove",
				"pos": (0, 0),
				"xalign": "left",
				"yalign": "top",
				"autoDir": False,
			},
			{
				"imageName": "resize-small.svg",
				"onClick": "startResize",
				"pos": (1, 1),
				"xalign": "right",
				"yalign": "buttom",
				"autoDir": False,
			},
		],
	),
	OptionData(
		name="",
		v3Name="dcalWinWidgetButtons",
		flags=0,
		type="list[DayCalWidgetButtonDict]",
		where="",
		desc="",
		default=[
			{
				"imageName": "transform-move.svg",
				"onClick": "startMove",
				"pos": (0, 0),
				"xalign": "left",
				"yalign": "top",
				"autoDir": False,
			},
			{
				"imageName": "resize-small.svg",
				"onClick": "startResize",
				"pos": (1, 1),
				"xalign": "right",
				"yalign": "buttom",
				"autoDir": False,
			},
			{
				"imageName": "document-edit.svg",
				"onClick": "openCustomize",
				"pos": (0, 1),
				"xalign": "left",
				"yalign": "buttom",
				"autoDir": False,
			},
		],
	),
	OptionData(
		name="",
		v3Name="menuIconEdgePadding",
		flags=0,
		type="int",
		where="",
		desc="",
		default=3,
	),
	OptionData(
		name="",
		v3Name="rightPanelEventIconSize",
		flags=0,
		type="int",
		valid="IntSpin(5, 128, 1)",
		where="",
		desc="",
		default=20,
	),
	OptionData(
		name="",
		v3Name="eventTreeIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=22,
	),
	OptionData(
		name="",
		v3Name="menuEventCheckIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=20,
	),
	OptionData(
		name="",
		v3Name="toolbarIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=24,
	),
	OptionData(
		name="",
		v3Name="mcalEventIconSizeMax",
		flags=0,
		type="int",
		where="",
		desc="",
		default=26,
	),
	OptionData(
		name="",
		v3Name="messageDialogIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=48,
	),
	OptionData(
		name="",
		v3Name="menuCheckSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=22,
	),
	OptionData(
		name="",
		v3Name="menuIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=18,
	),
	OptionData(
		name="",
		v3Name="comboBoxIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=20,
	),
	OptionData(
		name="",
		v3Name="imageInputIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=32,
	),
	OptionData(
		name="",
		v3Name="maxWeekCacheSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=12,
	),
	OptionData(
		name="",
		v3Name="wcalPadding",
		flags=0,
		type="int",
		where="",
		desc="",
		default=10,
	),
	OptionData(
		name="",
		v3Name="buttonIconSize",
		flags=0,
		type="int",
		where="",
		desc="",
		default=20,
	),
	OptionData(
		name="",
		v3Name="wcalEventIconSizeMax",
		flags=0,
		type="int",
		where="",
		desc="",
		default=26,
	),
	OptionData(
		name="",
		v3Name="eventWeekViewTimeFormat",
		flags=0,
		type="str",
		where="",
		desc="",
		default="HM$",
	),
]
