# Copyright (C) Saeed Rasooli <saeed.gnu@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.

from __future__ import annotations

from scal3.color_utils import RGBA
from scal3.ui.options._base import CUSTOMIZE, LIVE, OptionData

confOptionsData: list[OptionData] = [
	# ------------ Month Calendar
	OptionData(
		name="monthCal.leftMargin",
		v3Name="mcalLeftMargin",
		flags=CUSTOMIZE,
		type="int",
		valid="IntSpin(0, 999, 1)",
		where="MainWin: Customize: Month Calendar",
		desc="Left Margin",
		default=30,
	),
	OptionData(
		name="monthCal.topMargin",
		v3Name="mcalTopMargin",
		flags=CUSTOMIZE,
		type="int",
		valid="IntSpin(0, 999, 1)",
		where="MainWin: Customize: Month Calendar",
		desc="Top Margin",
		default=30,
	),
	OptionData(
		name="monthCal.typeOptions",
		v3Name="mcalTypeParams",
		flags=CUSTOMIZE,
		type="list[CalTypeOptionsDict]",
		where="MainWin: Customize: Month Calendar",
		desc="Calendar Types Options",
		default=[
			{"pos": (0, -2), "font": None, "color": (220, 220, 220)},
			{"pos": (18, 5), "font": None, "color": (165, 255, 114)},
			{"pos": (-18, 4), "font": None, "color": (0, 200, 205)},
		],
	),
	OptionData(
		name="monthCal.grid",
		v3Name="mcalGrid",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Month Calendar",
		desc="Grid",
		default=False,
	),
	OptionData(
		name="monthCal.gridColor",
		v3Name="mcalGridColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Month Calendar",
		desc="Grid Color",
		default=RGBA(255, 252, 0, 82),
	),
	OptionData(
		name="monthCal.cornerMenuTextColor",
		v3Name="mcalCornerMenuTextColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Month Calendar",
		desc="Corner Menu Text Color",
		default=RGBA(255, 255, 255, 255),
	),
	OptionData(
		name="monthCal.cursorLineWidthFactor",
		v3Name="mcalCursorLineWidthFactor",
		flags=CUSTOMIZE,
		type="float",
		valid="FloatSpin(0, 1, 0.1, 2)",
		where="MainWin: Customize: Month Calendar: Cursor",
		desc="Line Width Factor",
		default=0.12,
	),
	OptionData(
		name="monthCal.cursorRoundingFactor",
		v3Name="mcalCursorRoundingFactor",
		flags=CUSTOMIZE,
		type="float",
		valid="FloatSpin(0, 1, 0.1, 2)",
		where="MainWin: Customize: Month Calendar: Cursor",
		desc="Rounding Factor",
		default=0.5,
	),
	# ------------ weekcal
	OptionData(
		name="weekCal.textSizeScale",
		v3Name="wcalTextSizeScale",
		flags=CUSTOMIZE,
		type="float",
		valid="FloatSpin(0.01, 1, 0.1, 3)",
		where="MainWin: Customize: Week Calendar",
		desc="Text Size Scale",
		default=0.6,
	),
	OptionData(
		name="weekCal.items",
		v3Name="wcalItems",
		flags=CUSTOMIZE,
		type="list[tuple[str, bool]]",
		where="MainWin: Customize: Week Calendar",
		desc="Items",
		default=[
			("toolbar", True),
			("weekDays", True),
			("pluginsText", True),
			("eventsIcon", True),
			("eventsText", True),
			("daysOfMonth", True),
		],
	),
	OptionData(
		name="weekCal.grid",
		v3Name="wcalGrid",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar",
		desc="Grid",
		default=False,
	),
	OptionData(
		name="weekCal.gridColor",
		v3Name="wcalGridColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Week Calendar",
		desc="Grid Color",
		default=RGBA(255, 252, 0, 82),
	),
	OptionData(
		name="weekCal.upperGradientEnable",
		v3Name="wcalUpperGradientEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar",
		desc="Row's Upper Gradient",
		default=False,
	),
	OptionData(
		name="weekCal.upperGradientColor",
		v3Name="wcalUpperGradientColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Week Calendar",
		desc="Row's Upper Gradient: Color",
		default=RGBA(255, 255, 255, 60),
	),
	OptionData(
		name="weekCal.upperGradientSize",
		v3Name="wcalUpperGradientSize",
		flags=CUSTOMIZE,
		type="float",
		where="MainWin: Customize: Week Calendar",
		desc="Row's Upper Gradient: Size",
		default=0.5,
	),
	OptionData(
		name="weekCal.eventsText.pastColorEnable",
		v3Name="wcal_eventsText_pastColorEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Events Text",
		desc="Past Event Color",
		default=False,
	),
	OptionData(
		name="weekCal.eventsText.pastColor",
		v3Name="wcal_eventsText_pastColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Week Calendar: Columns: Events Text",
		desc="Past Event Color",
		default=RGBA(100, 100, 100, 50),
	),
	OptionData(
		name="weekCal.eventsText.ongoingColorEnable",
		v3Name="wcal_eventsText_ongoingColorEnable",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Events Text",
		desc="Ongoing Event Color",
		default=False,
	),
	OptionData(
		name="weekCal.eventsText.ongoingColor",
		v3Name="wcal_eventsText_ongoingColor",
		flags=CUSTOMIZE,
		type="ColorType",
		where="MainWin: Customize: Week Calendar: Columns: Events Text",
		desc="Ongoing Event Color",
		default=RGBA(80, 255, 80, 255),
	),
	OptionData(
		name="weekCal.eventsText.showDesc",
		v3Name="wcal_eventsText_showDesc",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Events Text",
		desc="Show Description",
		default=False,
	),
	OptionData(
		name="weekCal.eventsText.colorize",
		v3Name="wcal_eventsText_colorize",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: ",
		desc="Use color of event group for event text",
		default=True,
	),
	OptionData(
		name="weekCal.eventsText.fontFamily",
		v3Name="wcalFont_eventsText",
		flags=CUSTOMIZE,
		type="str | None",
		where="MainWin: Customize: Week Calendar: Columns: ",
		desc="Font Family",
		default=None,
	),
	OptionData(
		name="weekCal.toolbar.weekNumNegative",
		v3Name="wcal_toolbar_weekNum_negative",
		flags=LIVE,
		type="bool",
		where="MainWin: Week Calendar: Toolbar",
		desc="Week number is negated by clicking",
		default=False,
	),
	OptionData(
		name="weekCal.toolbar.mainMenuIcon",
		v3Name="wcal_toolbar_mainMenu_icon",
		flags=CUSTOMIZE,
		type="str",
		where="MainWin: Customize: Week Calendar: Columns: Toolbar: Main Menu",
		desc="Icon",
		default="starcal.png",
	),
	OptionData(
		name="weekCal.weekDays.width",
		v3Name="wcal_weekDays_width",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Week Calendar: Columns: Week Days",
		desc="Width",
		default=80,
	),
	OptionData(
		name="weekCal.weekDays.expand",
		v3Name="wcal_weekDays_expand",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Week Days",
		desc="Expand",
		default=False,
	),
	OptionData(
		name="weekCal.weekDays.fontFamily",
		v3Name="wcalFont_weekDays",
		flags=CUSTOMIZE,
		type="str | None",
		where="MainWin: Customize: Week Calendar: Columns: Week Days",
		desc="Font Family",
		default=None,
	),
	OptionData(
		name="weekCal.pluginsText.fontFamily",
		v3Name="wcalFont_pluginsText",
		flags=CUSTOMIZE,
		type="str | None",
		where="MainWin: Customize: Week Calendar: Columns: Plugins Text",
		desc="Font Family",
		default=None,
	),
	OptionData(
		name="weekCal.pluginsText.firstLineOnly",
		v3Name="wcal_pluginsText_firstLineOnly",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Plugins Text",
		desc="Only first line of text",
		default=False,
	),
	OptionData(
		name="weekCal.eventsIcon.width",
		v3Name="wcal_eventsIcon_width",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Week Calendar: Columns: Events Icon",
		desc="Width",
		default=50,
	),
	OptionData(
		name="weekCal.daysOfMonth.typeOptions",
		v3Name="wcalTypeParams",
		flags=CUSTOMIZE,
		type="list[WeekCalDayNumOptionsDict]",
		where="MainWin: Customize: Week Calendar: Columns: Days of Month",
		desc="Font (for each calendar type)",
		default=[{"font": None}, {"font": None}, {"font": None}],
	),
	OptionData(
		name="weekCal.daysOfMonth.direction",
		v3Name="wcal_daysOfMonth_dir",
		flags=CUSTOMIZE,
		type="str",  # ltr, rtl, auto
		where="MainWin: Customize: Week Calendar: Columns: Days of Month",
		desc="Direction",
		default="ltr",
	),
	OptionData(
		name="weekCal.daysOfMonth.width",
		v3Name="wcal_daysOfMonth_width",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Week Calendar: Columns: Days of Month",
		desc="Width",
		default=30,
	),
	OptionData(
		name="weekCal.daysOfMonth.expand",
		v3Name="wcal_daysOfMonth_expand",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: ",
		desc="Width",
		default=False,
	),
	OptionData(
		name="weekCal.eventsCount.width",
		v3Name="wcal_eventsCount_width",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Week Calendar: Columns: ",
		desc="Width",
		default=80,
	),
	OptionData(
		name="weekCal.eventsCount.expand",
		v3Name="wcal_eventsCount_expand",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: ",
		desc="Expand",
		default=False,
	),
	OptionData(
		name="weekCal.eventsBox.fontFamily",
		v3Name="wcalFont_eventsBox",
		flags=CUSTOMIZE,
		type="str | None",
		where="MainWin: Customize: Week Calendar: Columns: Events Box",
		desc="Font Family",
		default=None,
	),
	OptionData(
		name="weekCal.moonStatus.width",
		v3Name="wcal_moonStatus_width",
		flags=CUSTOMIZE,
		type="int",
		where="MainWin: Customize: Week Calendar: Columns: Moon Status",
		desc="Width",
		default=48,
	),
	OptionData(
		name="weekCal.moonStatus.southernHemisphere",
		v3Name="wcal_moonStatus_southernHemisphere",
		flags=CUSTOMIZE,
		type="bool",
		where="MainWin: Customize: Week Calendar: Columns: Moon Status",
		desc="Southern Hemisphere",
		default=False,
	),
	OptionData(
		name="weekCal.cursorLineWidthFactor",
		v3Name="wcalCursorLineWidthFactor",
		flags=CUSTOMIZE,
		type="float",
		valid="FloatSpin(0, 1, 0.1, 2)",
		where="MainWin: Customize: Week Calendar: Cursor",
		desc="Line Width Factor",
		default=0.12,
	),
	OptionData(
		name="weekCal.cursorRoundingFactor",
		v3Name="wcalCursorRoundingFactor",
		flags=CUSTOMIZE,
		type="float",
		valid="FloatSpin(0, 1, 0.1, 2)",
		where="MainWin: Customize: Week Calendar: Cursor",
		desc="Rounding Factor",
		default=0.5,
	),
]
