#!/bin/bash
cd /usr/bin
if [ ! -f python3 ] ; then
	echo "python3 command not found"
	for V in 3.3 3.2 3.1 3.0 ; do
		if [ -f "python$V" ] ; then
			ln -s "python$V" python3
			echo "LINKING /usr/bin/python$V TO /usr/bin/python3"
			break
		fi
	done
fi
cd - > /dev/null

