#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

daemon_name=starcal2d
daemon_desc="StarCal2 Daemon"
PIDFILE=/var/run/$daemon_name.pid
PID=$(cat $PIDFILE 2>/dev/null)
#echo "${1}ing: PID=$PID"
#if ! readlink -q /proc/$PID/exe | grep -q "\^$daemon_name"; then
#    echo "${1}ing: process not found"
#    PID=
#    rm $PIDFILE 2>/dev/null
#fi

case "$1" in
    start)
        stat_busy "Starting $daemon_desc"
        [ -z "$PID" ] && /usr/share/starcal2/scal2/starcal2-daemon.py &
        if [ $? -gt 0 ]; then
            stat_fail
        else
            add_daemon $daemon_name
            stat_done
        fi
        ;;
    stop)
        stat_busy "Stopping $daemon_desc"
        [ ! -z "$PID" ] && kill $PID &>/dev/null
        rm $PIDFILE 2>/dev/null
        if [ $? -gt 0 ]; then
            stat_fail
        else
            rm_daemon $daemon_name
            stat_done
        fi
        ;;
    restart)
        $0 stop
        sleep 1 ## enough? FIXME
        $0 start
        ;;

    status)
        stat_busy "Checking $daemon_name status";
        ck_status $daemon_name
        ;;

    *)
        echo "usage: $0 {start|stop|restart|status}"    
esac
exit 0
