#!/usr/bin/env python3
#
# Copyright (C) Saeed Rasooli <saeed.gnu@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

"""
Generate a sample "Menstrual Cycle" group JSON file for StarCal.

The generated file can be imported via the Event Manager
(Event Manager -> Import -> JSON (StarCalendar)).

By default it records one year of periods ending near the present day using a
regular cycle; pass the number of cycles to record as an optional argument.

Usage:
    python3 tools/generate_menstrual_sample.py [--cycles N] [--output FILE]
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from datetime import datetime
from os.path import abspath, dirname
from typing import TYPE_CHECKING, Any, cast

rootDir = dirname(dirname(abspath(__file__)))
sys.path.insert(0, rootDir)

from scal3.cal_types import GREGORIAN, to_jd  # noqa: E402
from scal3.event_lib import state  # noqa: E402
from scal3.event_lib.handler import Handler  # noqa: E402
from scal3.event_lib.state import InfoWrapper, LastIdsWrapper  # noqa: E402
from scal3.filesystem import DefaultFileSystem  # noqa: E402

if TYPE_CHECKING:
	from scal3.event_lib.menstrual import (  # noqa: E402
		MenstrualCycleGroup,
		MenstrualObservationEvent,
		MenstrualPeriodEvent,
	)


def generate_sample(
	cycles: int,
	cycleLength: int,
	periodLength: int,
	lutealPhase: int,
	personName: str,
) -> dict[str, Any]:
	"""Build the sample group data using a throwaway isolated filesystem."""
	tmpDir = tempfile.mkdtemp(prefix="starcal-menstrual-sample-")
	filesystem = DefaultFileSystem(tmpDir)
	for directory in ("event/events", "event/groups", "event/accounts", "objects"):
		filesystem.makeDir(directory)

	state.allReadOnly = False
	state.info = InfoWrapper.s_load(0, fs=filesystem)
	state.lastIds = LastIdsWrapper.s_load(0, fs=filesystem)
	try:
		handler = Handler()
		handler.init(filesystem)

		group = cast(
			"MenstrualCycleGroup",
			handler.groups.create("menstrualCycle"),
		)
		group.fs = filesystem
		group.setTitle("Menstrual Cycle (Sample)")
		group.personName = personName
		group.cycleLength = cycleLength
		group.cycleLengthAuto = False  # keep the predictions regular
		group.periodLength = periodLength
		group.lutealPhase = lutealPhase
		group.setRandomColor()
		group.save()
		handler.groups.append(group)

		today = to_jd(*datetime.now().timetuple()[:3], GREGORIAN)
		lastStart = today - 3
		starts = [lastStart - i * cycleLength for i in range(cycles)]
		starts.reverse()

		for startJd in starts:
			event = cast(
				"MenstrualPeriodEvent",
				group.create("menstrualPeriod"),
			)
			event.fs = filesystem
			event.setJd(startJd)
			event.setId()
			event.save()
			group.append(event)

		# demonstrate a manual adjustment: shift the most recent ovulation
		mostRecent = cast(
			"MenstrualPeriodEvent",
			group.getPeriodStartEvents()[-1],
		)
		ovulationOverride = group.predictOvulationForCycle(mostRecent.getJd())
		assert ovulationOverride is not None
		mostRecent.ovulationOverride = ovulationOverride + 1
		mostRecent.save()

		# a few observations logged by the woman or her partner
		recent = starts[-1]
		observations = [
			(recent + 2, "woman", "medium", "creamy", 36.5, "", False),
			(recent + 5, "woman", "none", "watery", 36.4, "", False),
			(recent + 7, "woman", "none", "eggwhite", 36.3, "positive", True),
			(recent + 8, "partner", "none", "eggwhite", None, "positive", True),
		]
		for jd, recordedBy, flow, mucus, bbt, opk, sex in observations:
			observation = cast(
				"MenstrualObservationEvent",
				group.create("menstrualObservation"),
			)
			observation.fs = filesystem
			observation.setJd(jd)
			observation.recordedBy = recordedBy
			observation.flow = flow
			observation.mucus = mucus
			observation.bbt = bbt
			observation.opk = opk
			observation.sex = sex
			observation.setId()
			observation.save()
			group.append(observation)

		group.updateOccurrence()

		assert group.id is not None
		data = handler.groups.exportData([group.id])
		# derived events (fertile window, ovulation, predicted periods) are
		# regenerated by the group on import, so keep the file free of them
		groupData = data["groups"][0]
		groupData["events"] = [
			eventData
			for eventData in groupData["events"]
			if eventData["type"] == "menstrualObservation"
			or (
				eventData["type"] == "menstrualPeriod"
				and not eventData.get("predicted")
			)
		]
		return data
	finally:
		state.allReadOnly = False
		state.info = None
		state.lastIds = None
		shutil.rmtree(tmpDir, ignore_errors=True)


def main() -> None:
	parser = argparse.ArgumentParser(
		description="Generate a sample Menstrual Cycle group JSON for StarCal.",
	)
	parser.add_argument(
		"--cycles",
		type=int,
		default=6,
		help="number of recorded cycles (default: 6)",
	)
	parser.add_argument(
		"--output",
		default="menstrual-sample.json",
		help="output JSON file path (default: menstrual-sample.json)",
	)
	parser.add_argument("--cycle-length", type=int, default=28)
	parser.add_argument("--period-length", type=int, default=5)
	parser.add_argument("--luteal-phase", type=int, default=14)
	parser.add_argument(
		"--person",
		default="Sample",
		help="name of the tracked person (default: Sample)",
	)
	args = parser.parse_args()

	if args.cycles < 1:
		parser.error("--cycles must be at least 1")
	if args.cycle_length < 15 or args.cycle_length > 60:
		parser.error("--cycle-length must be between 15 and 60")

	data = generate_sample(
		cycles=args.cycles,
		cycleLength=args.cycle_length,
		periodLength=args.period_length,
		lutealPhase=args.luteal_phase,
		personName=args.person,
	)
	with open(args.output, "w", encoding="utf-8") as fp:
		json.dump(data, fp, indent=1, ensure_ascii=False)

	groupData = data["groups"][0]
	eventCount = len(groupData["events"])
	print(f"Wrote {args.output}")
	print(f"  group: {groupData['title']!r}, events: {eventCount}")
	print(
		"  Import via Event Manager -> Import -> JSON (StarCalendar).",
	)


if __name__ == "__main__":
	main()
