#!/usr/bin/python
version='1.3.5'

shownDates[0]['color'] = gtk.gdk.Color(0, 0, 0)
shownDates[1]['color'] = gtk.gdk.Color(0, 40000, 0)
shownDates[2]['color'] = gtk.gdk.Color(0, 0, 50000)

fontCustom="Terafik 12"
fontUseDefault=True
calGrid=True
gridAlpha=9000
gridColor=gtk.gdk.Color(0, 0, 0)
prevStock="gtk-go-back"
nextStock="gtk-go-forward"
#bgUseDesk=True
bgColor=gtk.gdk.Color(65535, 65535, 65535)
bgColorAlpha=40000
borderColor=gtk.gdk.Color(0, 37000, 0)
borderColorAlpha=30000
borderTextColor=gtk.gdk.Color(65535, 65535, 65535)
holidayColor=gtk.gdk.Color(60000, 10535, 10000)
inactiveColor=gtk.gdk.Color(0, 0, 0)
cursorOutColor=gtk.gdk.Color(42565, 0, 42235)
cursorBgColor=gtk.gdk.Color(65535, 65535, 65535)
cursorBgAlpha=49000
calLeftMargin=30
calTopMargin=30
cursorD=3.0
cursorFixed=False
cursorW=57
cursorH=24

