name: "ArchLinux package"

on:
  push:
    branches: ["main", "next", "build-package"]
  workflow_dispatch:

jobs:
  build:
    name: "Build ArchLinux package"
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install build dependencies
        run: |
          pacman -Sy --noconfirm git gettext fakeroot binutils file gawk
      - name: Create build user
        run: |
          useradd --shell=/bin/bash build
          chown -R build "$GITHUB_WORKSPACE"
      - name: Build package
        env:
          STARCAL_XFCE_APPLET: "no"
        run: |
          mkdir -p /tmp/starcal3-out
          chown build /tmp/starcal3-out
          su build -c "$GITHUB_WORKSPACE/distro/archlinux/build.sh /tmp/starcal3-out /usr/bin/python3"
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: starcal3-archlinux
          path: /tmp/starcal3-out/*.pkg.tar*