name: "mypy"

on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
  schedule:
    - cron: "33 1 * * 3"

jobs:
  gen:
    name: "Run mypy --strict"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Download dependencies
        run: |
          python -m pip install mypy pygobject-stubs \
            --no-cache-dir --config-settings=config=Gtk3,Gdk3,Soup2
          python -m pip install types-requests types-python-dateutil types-pytz types-cachetools types-psutil
          mypy --install-types
      - name: Run mypy --strict
        run: |
          mypy . --strict --disallow-any-generics


