name: "Ruff"

on:
  push:
    branches: ["main", "next"]
  pull_request:
    branches: ["main", "next"]
  schedule:
    - cron: "33 1 * * 3"

jobs:
  ruff:
    name: "See: docs.astral.sh/ruff"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cd and ls
        run: |
          cd ${{ github.workspace }}
          ls -l
      - name: Download ruff
        run: |
          wget -c https://github.com/astral-sh/ruff/releases/download/0.12.4/ruff-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf ruff-*.tar.gz
          mv ruff-x86_64-unknown-linux-gnu/ruff .
          ls -l ruff
          chmod a+x ruff
      - name: Run ruff
        run: ./ruff check
